### ISSUE TITLE
Handling load_our_module() in environments lacking /lib/modules/`uname -r`

### ISSUE THREAD

**Issue by pkalever** [open-iscsi/tcmu-runner#145]
In some container environments the HOST /lib/modules/`uname -r` will not be bind mounted in the container, in such environments kmod_module_new_from_lookup() will error out. So even if target_core_user is loaded already, tcmu-runner will bail out.

Possible solutions:
1. Provide option '--no-load-module' for tcmu-runner which will skip calling load_our_module()
2. In load_our_module() check if /lib/modules/`uname -r` dir exist, if not exist return 0; 
    Pre assuming (leaving load module job as a prerequisite on HOST) the module already loaded.
3. Make insmod of target_core_user a prerequisite to tcmu-runner and get out of this mess.

Any better suggestions will definitely appreciable!

**Comment by pkalever** [comment]
@mikechristie @lxbsz  Thoughts ?

**Comment by mikechristie** [comment]
How does tcmu-runner start in this environment?

Does it also use systemd?

I like the idea of #3. What will load the module? Are you thinking of relying on the target service (tcmu-runner then relies on target) to make sure all the target modules including target_core_user are loaded?

**Comment by vbellur** [comment]
I think @pkalever is referring to leaving the prerequisite to the user.

Alternately can we read /proc/modules or /sys/module and look for the presence of target_core_user?

**Comment by vbellur** [comment]
A possible diff that can let tcmu-runner work in containers:

diff --git a/main.c b/main.c
index 1eed47b..cc6cf01 100644
--- a/main.c
+++ b/main.c
@@ -464,6 +464,13 @@ static int load_our_module(void)
        struct kmod_list *list = NULL, *itr;
        struct kmod_ctx *ctx;
        int ret;
+        struct stat stbuf;
+
+        ret = stat("/sys/module/target_core_user", &stbuf);
+        if (!ret) {
+                tcmu_dbg("Module already loaded\n");
+                return ret;
+        }
 
        ctx = kmod_new(NULL, NULL);
        if (!ctx) {

**Comment by mikechristie** [comment]
What do you mean by the user and how would that work then? You don't mean the user would do modprobe target_core_user before starting tcmu-runner right? In your case, does the user always start tcmu-runner manually then too?

For your patch, I thought this was supposed to do what your patch does:
https://github.com/open-iscsi/tcmu-runner/commit/4ad234084ef3cf865a5ba4b8a09df546264c034e

**Comment by vbellur** [comment]
Yes, I intended that user would ensure that target_core_user is modprobed before starting tcmu-runner.

Typically In containers, tcmu-runner would be expected to start running as soon as the container launches. A sample dockerfile that starts gluster-blockd.service and hence tcmu-runner can be found at:

https://github.com/gluster/gluster-containers/pull/36/files

4ad2340 works if the default directory that kmod_new() looks up (/lib/modules/`uname -r`) is available in the container. For reasons that I do not understand yet, neither /lib/modules or /usr/lib/modules is available in a running container. I have not figured out a way in which libkmod apis could be used to work when either of these modules directories is not present. Hence the explicit stat() to help  containers that already have target_core_user loaded in the kernel.

**Comment by mikechristie** [comment]
Ok, funny. I see the mention to kmod_module_new_from_lookup() failing above now. The patch description just mentions containers so many times, I thought the point of the patch was to catch the problem in containers :)

The stat patch seems fine to me.

**Comment by pkalever** [comment]
In the upstream Kubernetes containers platform it is very much okay to have `/lib/modules/uname-r` bind mounted in/to the container. But in the openshift it seems a bit hacky  and not acceptable.
As vijay mentioned it above the patch 4ad2340 works fine, provided this directory is available. This PR is to get to an accepted solution on how tcmu-runner should behave if the modules dir is not available in containers :)

**Comment by mikechristie** [comment]
Not exactly fixed, but resolution was to have admin or something else handle the problem. runner just warns the user:

commit 203e23966cdbd48e9e12de58e9611d046a0101eb
Author: Prasanna Kumar Kalever <prasanna.kalever@redhat.com>
Date:   Sun May 21 16:53:23 2017 +0530

    load_module: defend on modules directory
