### ISSUE TITLE
glfs handler is opening the block file using O_SYNC even though FLUSH op does fdatasync

### ISSUE THREAD

**Issue by pranithk** [open-iscsi/tcmu-runner#149]
I am just familiarizing myself with tcmu code and I see that there is an op called FLUSH which is doing fdatasync() for glfs handler. but we are still using O_SYNC in the open/write/read flags.

in glfs.c
#define ALLOWED_BSOFLAGS (O_SYNC | O_DIRECT | O_RDWR | O_LARGEFILE)

I feel it is redundant to have O_SYNC if we are going to anyway get FLUSH operations.

What do you guys think? @mikechristie @pkalever

**Comment by mikechristie** [comment]
Does SYNC and DIRECT mean the same thing in gluster as when you use them to open a block device in linux? If so, then yeah, then doing a SYNCHRONIZE CACHE (tcmu runner handler->flush) call would not be needed.

If you were going to remove the flush callout I think you need this patch, so the initiator knows there are no caches in use.

[runner-cache.txt](https://github.com/open-iscsi/tcmu-runner/files/999888/runner-cache.txt)

**Comment by pranithk** [comment]
@mikechristie gluster-block is a file on glusterfs, so all the flags like O_SYNC|O_DIRECT are same as for a file on linux. So cache won't be used. I think it is better to use cache and SYNCHRONIZE CACHE than to disable it. So I was wondering if we can remove O_SYNC.

**Comment by mikechristie** [comment]
Looks resolved in PR #159
