### ISSUE TITLE
Segmentation fault when adding a rbd backstore

### ISSUE THREAD

**Issue by DaFresh** [open-iscsi/tcmu-runner#173]
The context : kernel 4.9, tmcu-runner/configshell-fb/rtslib-fb/targetcli-fb from master, ceph 10.2.5.

rbd image 'img1':
        size 2048 MB in 512 objects
        order 22 (4096 kB objects)
        block_name_prefix: rbd_data.103a6b8b4567
        format: 2
        features: layering, exclusive-lock, object-map, fast-diff, deep-flatten
        flags: 

Adding a rbd backstore with "create cfgstring=rbd/img1 size=2G name=img1" succeed in targetcli but make tcmu-runner segfault, see attached file for trace.

[trace.txt](https://github.com/open-iscsi/tcmu-runner/files/1063689/trace.txt)

As a note I have been able to successfully create the rbd backstore in the exact same context except I had other configuration already in place (fileio backstore and iscsi config), but I cannot reproduce it, and it was not a working configuration (last messages on issue #168 )

**Comment by mikechristie** [comment]
Could you try the patches in this PR:

https://github.com/open-iscsi/tcmu-runner/pull/175

It looks like you might be failing when we run a debug log command and I noticed some bugs in there while reviewing the code.

**Comment by DaFresh** [comment]
Same error with #175 applied, I re-attach a trace if it could help.
[trace.txt](https://github.com/open-iscsi/tcmu-runner/files/1066361/trace.txt)

**Comment by mikechristie** [comment]
Is the handler_rbd.so plugin located here:

/usr/local/lib/tcmu-runner/handler_rbd.so

the same one that you just built or is it a one that was installed from a previous install/build?

Where is the libtcmu that you are using too? Is the one here

/usr/src/tcmu-runner/libtcmu.so.1

the one that goes with the tcmu-runner that you are currently building and testing or from a previous build?

**Comment by DaFresh** [comment]
As you said, handler_rbd.so and libtcmu.so.1 were from an old build, nice catch.

Thanks
