### ISSUE TITLE
Can't compile on CentOS 7

### ISSUE THREAD

**Issue by nickcn** [open-iscsi/tcmu-runner#179]
Hello,

I'm trying to compile tcmu-runner on CentOS 7 and, having installed all the required packages, it doesn't compile. The output of make is this:

> [  4%] Generating tcmuhandler-generated.c, tcmuhandler-generated.h
> Scanning dependencies of target tcmu
> [  8%] Building C object CMakeFiles/tcmu.dir/api.c.o
> [ 12%] Building C object CMakeFiles/tcmu.dir/libtcmu.c.o
> /root/tcmu-runner/libtcmu.c:31:36: fatal error: linux/target_core_user.h: No such file or directory
>  #include <linux/target_core_user.h>
>                                     ^
> compilation terminated.
> make[2]: *** [CMakeFiles/tcmu.dir/libtcmu.c.o] Error 1
> make[1]: *** [CMakeFiles/tcmu.dir/all] Error 2
> make: *** [all] Error 2

Any help is much appreciated.

**Comment by lxbsz** [comment]
You need copy the target_core_user.h from some where to your CentOS 7 system.

**Comment by nickcn** [comment]
The kernel-debug-devel and kernel-devel packages seem to provide target_core_user.h. I also have set CFLAGS to point to the uapi folder in my system.

**Comment by lxbsz** [comment]
The target_core_user.h is located in kernel's uapi/. For the rpm, it should be in kernel-headers package, but for the current rpms(I am using 3.10.0-514 version ), the target_core_user.h has been disabled by Redhat or CentOS when backporting(?), so for now I think we should manully copy it from the source code or some where.

**Comment by mikechristie** [comment]
The target_core_user module in RHEL 7.3 is what Red Hat calls tech preview. It basically means not tested and not supported. RHEL did not ship user space tools for it and did not include target_core_user.h in the header/uapi rpm, so like lxbsz said you need to copy it yourself.

**Comment by mikechristie** [comment]
We are also shipping target_core_user.h with tcmu-runner, so this should be fixed either way.

**Comment by nickcn** [comment]
I will try to compile again on Monday when at work, since I don't have access to my machine now. Thanks a lot.
