### ISSUE TITLE
Recommend separating rbd backend cfgstring options by ":" instead of "/" 

### ISSUE THREAD

**Issue by dillaman** [open-iscsi/tcmu-runner#253]
Commit ee33c404f6a8b56bd6ec5e6d2ad20386df93c3e7 added support for the "osd_op_timeout" option which is currently delineated by a "/" after the ```<pool>/<image>``` spec. Assuming we will add support for other options in the future, I propose using ":" as a delineator for options just like QEMU rbd option support [1].

[1] http://docs.ceph.com/docs/master/rbd/qemu-rbd/#usage

**Comment by mikechristie** [comment]
That sounds ok to me.

Would it be

pool/image/option1:option2:option3

Or

pool/image:option1:option2:option3

For the first one, I think we will be ok runner wise. Will there be future issues with new ceph options?

For the second one, I can respond to mails but cannot make a new release for a couple weeks, so for the ceph tools we could just code it like we are going to do option 2 and tell users to wait for runner v1.3.0-rc3.

**Comment by dillaman** [comment]
@mikechristie I was thinking ```pool/image:option1:option2:option3``` and it can definitely wait

**Comment by mikechristie** [comment]
Ended up using ";".

Patch is merged in  PR:

https://github.com/open-iscsi/tcmu-runner/pull/288
