### ISSUE TITLE
version 1.3.0-rc2: rbd image is still watched even though it is already deleted in targetcli

### ISSUE THREAD

**Issue by leeyc0** [open-iscsi/tcmu-runner#293]
I am testing tcmu-runner in testing environment, and I found a problem that I am unable to delete unused rbd image that was mapped using targetcli.

I created a backstore using
`targetcli /backstores/user:rbd create aaaa 1G iscsi/aaaaa`
and deleted it immediately
`targetcli /backstores/user:rbd delete aaaa`

Although it is deleted successfully, I found that the rbd image iscsi/aaaaa is still being watched:

```
[root@ctdb-test-1 ~]# rbd status iscsi/aaaaa
Watchers:
	watcher=10.41.41.118:0/3855162029 client.54188 cookie=140077674048528
	watcher=10.41.41.118:0/3947603200 client.54187 cookie=140078278028352
```

To fix this problem I have to restart tcmu-runner, which would be unacceptable in production environment.

**Comment by leeyc0** [comment]
Looks like fixed in master

**Comment by lxbsz** [comment]
#279 had fixed your issue.
