### ISSUE TITLE
Cant start daemon, no libtcmu.so.2

### ISSUE THREAD

**Issue by jorpilo** [open-iscsi/tcmu-runner#310]
I have installed on a CentOS 7 system but when trying to run it as roo it says:
tcmu-runner: error while loading shared libraries: libtcmu.so.2: cannot open shared object file: No such file or directory
libtcmu.so.2 exist in /user/lib/
what can I do?

**Comment by Jorpilo** [comment]
I solved myself by creating a symbolic link from /usr/lib/libtcmu.so.2 to /usr/lib64/

**Comment by mikechristie** [comment]
Did you have a previous install of tcmu-runner?

And did you use any make options like CMAKE_INSTALL_PREFIX or CMAKE_INSTALL_LIBDIR?

**Comment by mikechristie** [comment]
Closing due to lack of response. Reopen with needed info.
