### ISSUE TITLE
set_genl_features:278: Could not set features.

### ISSUE THREAD

**Issue by diluga** [open-iscsi/tcmu-runner#336]
./tcmu-runner
2017-11-22 18:13:13.887 30093 [INFO] dyn_config_start:409: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
2017-11-22 18:13:13.888 30093 [ERROR] set_genl_features:278: Could not set features. Error -10

 uname -a
Linux  4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.51-1~bpo8+1 (2017-10-17) x86_64 GNU/Linux

./tcmu-runner --version
tcmu-runner 1.3.0-rc4

dpkg -l|grep libnl
ii  libnl-3-200:amd64                      3.2.27-2                      amd64        library for dealing with netlink sockets
ii  libnl-3-200-dbg                        3.2.27-2                      amd64        debug symbols for libnl3
ii  libnl-3-dev:amd64                      3.2.27-2                      amd64        development library and headers for libnl-3
ii  libnl-genl-3-200:amd64                 3.2.27-2                      amd64        library for dealing with netlink sockets - generic netlink
ii  libnl-genl-3-dev:amd64                 3.2.27-2                      amd64        development library and headers for libnl-genl-3
ii  libnl-route-3-200:amd64                3.2.27-2                      amd64        library for dealing with netlink sockets - route interface
ii  libnl-route-3-dev:amd64                3.2.27-2                      amd64        development library and headers for libnl-route-3

it is a bug?

**Comment by pkalever** [comment]
It is not a bug. Just that you are using a kernel that does not support the sync add/delete.

**Comment by diluga** [comment]
thx,how to check my kernel support the sync add/delete?

**Comment by mikechristie** [comment]
4.13 and newer will have it.
