### ISSUE TITLE
iscsi login failed

### ISSUE THREAD

**Issue by vatelzh** [open-iscsi/tcmu-runner#354]
I'm using tcmu-runner(master) and kernel-4.14.6.
When I login the target in linux with iscsiadm, login command hangup, and I check the message in target server, /var/log/message

kernel: Initiator is requesting CSG: 1, has not been successfully authenticated, and the Target is enforcing iSCSI Authentication, login failed.
Jan 19 13:59:43 server3 kernel: iSCSI Login negotiation failed.
Jan 19 14:06:55 server3 kernel: Initiator is requesting CSG: 1, has not been successfully authenticated, and the Target is enforcing iSCSI Authentication, login failed.
Jan 19 14:06:55 server3 kernel: iSCSI Login negotiation failed.

**Comment by mikechristie** [comment]
This does not have anything to do with tcmu-runner. It only handles the device level stuff normally.

You basically do not have CHAP setup properly.

What are you using to setup the iscsi target? targetcli or ceph-iscsi-cli?

**Comment by mikechristie** [comment]
> You basically do not have CHAP setup properly.

Not necessarily you, but probably the tools did not set it up right :)

Assuming you are using ceph-isci-cli and you wanted to use CHAP, could you post the output of

targetcli ls

and

gwcli ls

and on the initiator side can you confirm that the output of

iscsiadm -m node -T your_target | grep auth

shows that the username and password are set.

Note there is a quirk in how auth is done in ceph-iscsi-cli. We cannot have some clietns/initiators using CHAP and some not using it. There is a patch to document that here:

https://github.com/ceph/ceph-iscsi-cli/pull/74

**Comment by vatelzh** [comment]
@mikechristie  reproduce another issue which is very similar with this one.

int gw1
gwcli command output:
o- hosts ........................................................................................................... [Hosts: 12]
      o- iqn.1994-05.com.redhat:91c68f1521c1 ............................................................ [Auth: CHAP, Disks: 1(0b)]
      | o- lun 0 ..................................... [rbd.volume-0103ac52-300d-4718-bb01-d99124898a9d(), Owner: gw2]

but in targetcli, I can't see this host.

in gw2
o- hosts ........................................................................................................... [Hosts: 12]
      o- iqn.1994-05.com.redhat:91c68f1521c1 ................................................. [LOGGED-IN, Auth: CHAP, Disks: 1(0b)]
      | o- lun 0 ..................................... [rbd.volume-0103ac52-300d-4718-bb01-d99124898a9d(), Owner: gw2]
targetcli output:
o- iqn.1994-05.com.redhat:91c68f1521c1 ...................................................... [1-way auth, Mapped LUNs: 1]
  |   | | | o- mapped_lun0 ............................. [lun11 user/rbd.volume-0103ac52-300d-4718-bb01-d99124898a9d (rw)]

I check the rbd-target-api log and tcmu-runner log, no ERROR message found.

**Comment by vatelzh** [comment]
this is environment issue...  closing it.
