### ISSUE TITLE
Active/Active is not supported: [WARN] tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1

### ISSUE THREAD

**Issue by letterwuyu** [open-iscsi/tcmu-runner#356]
Hi, I have apply patch on centos7.4 kernel 4.14.10 by https://www.spinics.net/lists/target-devel/msg16162.html, and Ceph-iscsi-api has been successfully deployed ，but， Sometimes “[WARN] tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1” should be issued when target is login，and  cannot be formatted  by mkfs.xfs -f,Is it where I have a problem, I am a little confused .

/var/log/message:
Jan 22 14:18:08 gw-1 tcmu-runner: tcmu_rbd_lock:629 rbd/rbd.disk1: Acquired exclusive lock.
Jan 22 14:18:08 gw-1 tcmu-runner: 2018-01-22 14:18:08.102 813 [WARN] tcmu_rbd_lock:629 rbd/rbd.disk1: Acquired exclusive lock.
Jan 22 14:18:09 gw-1 tcmu-runner: tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1
Jan 22 14:18:09 gw-1 tcmu-runner: 2018-01-22 14:18:09.127 813 [WARN] tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1
Jan 22 14:18:10 gw-1 tcmu-runner: tcmu_rbd_lock:629 rbd/rbd.disk1: Acquired exclusive lock.
Jan 22 14:18:10 gw-1 tcmu-runner: 2018-01-22 14:18:10.153 813 [WARN] tcmu_rbd_lock:629 rbd/rbd.disk1: Acquired exclusive lock.
Jan 22 14:18:11 gw-1 tcmu-runner: tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1
Jan 22 14:18:11 gw-1 tcmu-runner: 2018-01-22 14:18:11.174 813 [WARN] tcmu_notify_lock_lost:197 rbd/rbd.disk1: Async lock drop. Old state 1

**Comment by lxbsz** [comment]
Are you using the multipath ? And what's your multipath side configuration ?

**Comment by letterwuyu** [comment]
yes, i use the multipath
/dev/multipath.conf:
devices {
        device {
                vendor                 "LIO-ORG"
                hardware_handler       "1 alua"
                path_grouping_policy   "multibus"
                path_selector          "queue-length 0"
                failback               60
                path_checker           tur
                prio                   alua
                prio_args              exclusive_pref_bit
                no_path_retry          120
        }
}
My other initiator configuration is：
/etc/multipath.conf:
devices {
        device {
                vendor                 "LIO-ORG"
                hardware_handler       "1 alua"
                path_grouping_policy   "multibus"
                path_selector          "queue-length 0"
                failback               immediate
                path_checker           tur
                prio                   alua
                prio_args              exclusive_pref_bit
                no_path_retry          queue
        }
}

blacklist {
}

defaults {
}

**Comment by lxbsz** [comment]
Please refter to http://docs.ceph.com/docs/master/rbd/iscsi-initiator-linux/

 path_grouping_policy   "failover"

**Comment by letterwuyu** [comment]
Thinks your helpful， Does not it be unsupported that IO load balancing can only be the master mode （by path_grouping_policy "failover"）？

**Comment by lxbsz** [comment]
Currently due to the reasons for the design framework of the TCMU, only the failover policy is support.

**Comment by mikechristie** [comment]
> Hi, I have apply patch on centos7.4 kernel 4.14.10 by https://www.spinics.net/lists/target-devel/msg16162.html, 

@letterwuyu just a FYI, you probably want to use this kernel:

https://github.com/ceph/ceph-client/tree/ceph-iscsi-test

if you want something stable for your userspace development.

Or, use this the target-devel for-next branch:

https://git.kernel.org/pub/scm/linux/kernel/git/nab/target-pending.git/log/?h=for-next

if you are also going to be doing some kernel development.

Both kernels have the patches you need.

**Comment by letterwuyu** [comment]
@mikechristie  Thank you, your FYI is very useful for me， In fact, I was looking for the kernel with these patches before .

**Comment by mikechristie** [comment]
Closing this for now since we just do not support it and we do not have a way to support multibus any time soon.

**Comment by letterwuyu** [comment]
@mikechristie  sorry for bothering you，I want to ask, if I want tcmu-runner to support multibus, how difficult is the difficulty of development? Can you tell me the reason why we don't support multibus  at present.I want to know something about i and try to find a solution.

**Comment by mikechristie** [comment]
If you want to use LIO in a HA config where you export the rbd image through multiple LIO instances running on multiple nodes like what is setup with ceph-iscsi-*, and do multibus across the portals on the nodes then we cannot support that right now, because we do not have a way to handle IO retried through other nodes right now. The problem would be if WRITE1 to sector N was sent through portal 1 on node1, and it gets stuck in the runner/librbd layer (not yet sent to the ceph cluster). If the initiator side times it out, retries it though portal1 on node2, it succeeds, and then the initiator sends more successful writes to sector N, but then later the original WRITE1 is able to execute it will overwrite all the newer WRITEs to sector N. There are ideas to handle this, but we have not implemented them due to lack of time.

Are you a coder? If so, I can send some more info. Right now, there is not a admin level type of workaround. You would have to implement this feature.

**Comment by mslovy** [comment]
Thanks for your reply @mikechristie, @letterwuyu  and I is the coders and want to apply iscsi gateway as soon as possible in our production environment to serve our window servers as well as a vmware backend storage. I would be appreciated if you can send us more info and some ideas how to do that in tcmu-runner, we are happy to push on this features and upstream code for it.

**Comment by mikechristie** [comment]
> as soon as possible in our production environment to serve our window servers as well as a vmware backend storage.

Just to make sure we are on the same page. The current release allows for active/passive which is ok for production uses.

We are just talking about adding support for active/active. I will write up some info on that. I am actually on vacation until Feb 5th, but will try to write something up next Tues when I have access to my normal machines and not just my phone and laptop.

**Comment by jazeltq** [comment]
Fine，You writing will be very welcome

**Comment by zouyueming** [comment]
in logs i found tcmu-runner.log
2018-11-13 04:46:11.826 94190 [WARN] tcmu_get_alua_grp:210 rbd/rbd.image3: Unsupported alua_access_type: Explicit failover not supported.
2018-11-13 04:46:11.826 94190 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.image3: Could not get alua group ao.
2018-11-13 04:51:11.827 94190 [WARN] tcmu_get_alua_grp:210 rbd/rbd.image3: Unsupported alua_access_type: Explicit failover not supported.
2018-11-13 04:51:11.827 94190 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.image3: Could not get alua group ao.
2018-11-13 04:56:11.828 94190 [WARN] tcmu_get_alua_grp:210 rbd/rbd.image3: Unsupported alua_access_type: Explicit failover not supported.
2018-11-13 04:56:11.828 94190 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.image3: Could not get alua group ao.
2018-11-13 05:01:11.828 94190 [WARN] tcmu_get_alua_grp:210 rbd/rbd.image3: Unsupported alua_access_type: Explicit failover not supported.
2018-11-13 05:01:11.829 94190 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.image3: Could not get alua group ao.
2018-11-13 05:06:11.829 94190 [WARN] tcmu_get_alua_grp:210 rbd/rbd.image3: Unsupported alua_access_type: Explicit failover not supported.
2018-11-13 05:06:11.829 94190 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.image3: Could not get alua group ao.


what should i do ???  i need help

**Comment by mikechristie** [comment]
@zouyueming 

See here
https://github.com/open-iscsi/tcmu-runner/issues/369
