### ISSUE TITLE
targetcli user:file supports only < 2GB file on 32 bits Linux

### ISSUE THREAD

**Issue by ogck** [open-iscsi/tcmu-runner#358]
In targetcli, under /backstores/user:file

create disk 5G /var/disk.img
UserBackedStorageObject creation failed.

In target_core_user.c

struct tcmu_dev {
...
	size_t dev_size;
...
};

size_t is 32 bits in 32 bits Linux.

Can this be fixed?

**Comment by lxbsz** [comment]
I think yes and do you have any patch about this ?

**Comment by mikechristie** [comment]
Shoot. The dumb thing is that I did the resize code and updated tcmu_dev_size_store and just assumed everything was 64 bits already.

Here is a kernel patch to update the dev_size to 64 bits in the kernel. I will put up another patch to update runner everywhere.

[dev-size64.txt](https://github.com/open-iscsi/tcmu-runner/files/1654273/dev-size64.txt)


@ogck 

Where are you using tcmu-runner on a 32bit platform? Is it some sort of embedded storage device?

**Comment by mikechristie** [comment]
Ignore that patch.

Here is a user space fix and in the PR is a tested kernel fix:

https://github.com/open-iscsi/tcmu-runner/pull/360

Closing this issue. We can discuss on the PR.

**Comment by ogck** [comment]
Raspberry pi 0. Tcmu makes it a usb flash drive.

Cheers,
Chun
________________________________
