### ISSUE TITLE
compiling error, redefinition io_vec

### ISSUE THREAD

**Issue by ls-zhu** [open-iscsi/tcmu-runner#362]
When compile master branch latest code:
           
      from /home/lszhu/workspace/tcmu-runner/libtcmu.c:36:
/usr/include/linux/uio.h:17:8: error: redefinition of ‘struct iovec’
 struct iovec
        ^~~~~
In file included from /usr/include/bits/fcntl-linux.h:38:0,
                 from /usr/include/bits/fcntl.h:61,
                 from /usr/include/fcntl.h:35,
                 from /home/lszhu/workspace/tcmu-runner/libtcmu.c:20:
/usr/include/bits/types/struct_iovec.h:26:8: note: originally defined here
 struct iovec
        ^~~~~

Linux header conflicts with glibc, both included.

**Comment by ls-zhu** [comment]
I am trying to fix this.

**Comment by ls-zhu** [comment]
This can be reproduced in Both OpenSUSE and Fedora, for Fedora:
[lszhu@localhost tcmu-runner]$ rpm -qf /usr/include/linux/uio.h
kernel-headers-4.14.14-300.fc27.x86_64
@localhost tcmu-runner]$ rpm -qf /usr/include/fcntl.h
glibc-headers-2.26-24.fc27.x86_64

Lee's patch https://github.com/open-iscsi/tcmu-runner/pull/322/commits/209594010c5abbebd64c45a76c2a92dbe37024a3 works for me, can fix this, can we merge it?
@mikechristie @gonzoleeman

**Comment by mikechristie** [comment]
Closing as duplicate. We can discuss in the PR and other issue.
