### ISSUE TITLE
Need to remove "%define _RC rc4" in tcmu-runner.spec for version 1.3.0

### ISSUE THREAD

**Issue by rumanzo** [open-iscsi/tcmu-runner#364]
diff --git a/tcmu-runner.spec b/tcmu-runner.spec
index 25cd83c..25df5d6 100644
--- a/tcmu-runner.spec
+++ b/tcmu-runner.spec
@@ -5,7 +5,6 @@ License:       Apache 2.0
 Version:       1.3.0
 URL:           https://github.com/open-iscsi/tcmu-runner

-%define _RC rc4
 Release:       %{?_RC:%{_RC}}%{dist}
 BuildRoot:     %(mktemp -udp %{_tmppath}/%{name}-%{version}%{?_RC:-%{_RC}})
 Source:       %{name}-%{version}%{?_RC:-%{_RC}}.tar.gz

**Comment by mikechristie** [comment]
Thanks!

I think this will still have a problem where we rpm build wants a extra dash:

tcmu-runner-1.3.0-

@lxbsz Can we just kill all the RC related references and in the version just name it x.y.z-rcN or x.y for non RC?

**Comment by rumanzo** [comment]
You are right, it need release, i found it later.

**Comment by lxbsz** [comment]
@mikechristie 
Yes, agree. And I'm also thinking will it be better when we just use the HEAD commit ID instead of the tags, just like the gluster and others do ?

**Comment by lxbsz** [comment]
https://github.com/open-iscsi/tcmu-runner/pull/367
I just add one script to make it easier to build the RPMs and will delete the _RC in spec file only when building. @rumanzo please go on about this.

**Comment by mikechristie** [comment]
Patch has been merged. Closing this.
