### ISSUE TITLE
[ERROR] tcmu_get_alua_grp:201 rbd/rbd.disk1: device failover is not supported with the alua access type: Implicit

### ISSUE THREAD

**Issue by mikeeremin** [open-iscsi/tcmu-runner#369]
Hi,
i'am using ceph 12.2.2 on last Centos 7
tcmu-runner-1.3.0
kernel - 4.15.0-ceph-g1c778f43da52
All other packages - last versions from github, builded to rpms.
All setup via http://docs.ceph.com/docs/master/rbd/iscsi-target-cli/
There is no new block device, but login successful.

In messages i see:

Feb  7 13:43:22 st6-stat tcmu-runner: tcmu_get_alua_grp:201 rbd/rbd.disk1: device failover is not supported with the alua access type: Implicit
Feb  7 13:43:22 st6-stat: tcmu_get_alua_grps:303 rbd/rbd.disk1: Could not get alua group ano1.
Feb  7 13:43:22 st6-stat: tcmu-runner: 2018-02-07 13:43:22.561 2905 [ERROR] tcmu_get_alua_grp:201 rbd/rbd.disk1: device failover is not supported with the alua access type: Implicit
Feb  7 13:43:22 st6-stat: tcmu-runner: 2018-02-07 13:43:22.561 2905 [ERROR] tcmu_get_alua_grps:303 rbd/rbd.disk1: Could not get alua group ano1.

gwcli state in attached image

![gwcli](https://user-images.githubusercontent.com/574138/35912643-339400a2-0c0e-11e8-943a-89cb6b85f61c.png)

**Comment by mikechristie** [comment]
> Feb 7 13:43:22 st6-stat tcmu-runner: tcmu_get_alua_grp:201 rbd/rbd.disk1: device failover is not supported with the alua access type: Implicit

This message means the tcmu runner rbd handler was not built with rbd locking enabled.

1. Have you built/installed multiple versions of tcmu-runner? Search for handler_rbd.so. Do you just see the one copy?

2. Was tcmu-runner built against a older version of librbd1 or is there a older version of the headers/librbd-devel rpm installed? Check that:

rpm -q librbd1
matches
rpm -q librbd-devel

3. Could you attach the /usr/include/rbd/librbd.h that was on the machine used for rpm building, so I can check the version. In the runner rbd hanlder we need:

#if LIBRBD_VERSION_CODE >= LIBRBD_VERSION(0, 1, 11)
#define RBD_LOCK_ACQUIRE_SUPPORT
#endif

**Comment by mikeeremin** [comment]
Thanks for quick response, 
i found old versions of librbd* in my build host, 
but after updating to latest versions i still can't find needed variable in header file

[root@build repo]# rpm -qa | grep rbd
librbd-devel-12.2.2-0.el7.x86_64
librbd1-12.2.2-0.el7.x86_64
[root@build repo]# cat /usr/include/rbd/librbd.h | grep RBD_LOCK_ACQUIRE_SUPPORT
[root@build repo]#

So, i can't find it on latest github 
https://github.com/ceph/ceph/blob/master/src/include/rbd/librbd.h

**Comment by zouyueming** [comment]
#yum list installed |grep librbd
librbd-devel.x86_64                2:12.2.8-0.el7
librbd1.x86_64                        2:12.2.8-0.el7

**Comment by lxbsz** [comment]
Are you using the upstream tcmu-runner code here ? And how did you config/create the target devices ? 

This is none business with the librbd-devel package. It's just as the log error said: "Explicit only failover not supported". It should be one of "None", "Implicit" and "Implicit and Explicit", but yours here is "Explicit".

So yours is not the very same with this issue.

You could check the type of the ao alua group of your target devices, just like:
```
]# cat /sys/kernel/config/target/core/user_0/block0/alua/glfs_tg_pt_gp_ao/alua_access_type 
Implicit
]# 
```
Or
```
]# targetcli /backstores/user:rbd/rbd.image3/alua/XXX_tg_pt_gp_ao info
[...]
alua_access_type: 1
[...]
]#
```

**Comment by zouyueming** [comment]
I'm not very familiar with the operating system level,I used kylin 7.4's operating system（麒麟）, upgraded the kernel to 4.16, targetcli used the targetcli-fb version, ceph used the 12.2.8 version,

[root@ceph1 default_tg_pt_gp]# cat /sys/kernel/config/target/core/user_1/rbd.image1/alua/default_tg_pt_gp/alua_access_type
Implicit and Explicit

[root@ceph1 alua]# yum list installed |grep tcmu-runner
tcmu-runner.x86_64              1.3.0-rc4.el7.centos           @ceph-support

[root@ceph1 alua]# yum list installed |grep targetcli
targetcli-fb.noarch             2.1.fb48-1                     @ceph-support

[root@ceph1 alua]# uname -a
Linux ceph1 4.16.0-0.rc5.git0.1.el7.centos.x86_64 #1 SMP Tue Mar 13 21:06:55 CST 2018 x86_64 x86_64 x86_64 GNU/Linu

/iscsi-target...dc7d-2e91c819> cd /
/> ls
o- / ......................................................................................................................... [...]
  o- clusters ........................................................................................................ [Clusters: 1]
  | o- ceph ............................................................................................................ [HEALTH_OK]
  |   o- pools ......................................................................................................... [Pools: 12]
  |   | o- .rgw.root ....................................................................... [(x3), Commit: 0b/16.6T (0%), Used: 3K]
  |   | o- cephfs_data ..................................................................... [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   | o- cephfs_metadata ................................................................. [(x3), Commit: 0b/16.6T (0%), Used: 2K]
  |   | o- cinder-backups .................................................................. [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   | o- cinder-volumes ................................................................. [(x3), Commit: 0b/16.6T (0%), Used: 17b]
  |   | o- default.rgw.control ............................................................. [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   | o- default.rgw.log ................................................................. [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   | o- default.rgw.meta ................................................................ [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   | o- glance-images .................................................................. [(x3), Commit: 0b/16.6T (0%), Used: 39M]
  |   | o- nova-vms ....................................................................... [(x3), Commit: 0b/16.6T (0%), Used: 32M]
  |   | o- rbd .......................................................................... [(x3), Commit: 600G/16.6T (3%), Used: 50K]
  |   | o- rbd-1 ........................................................................... [(x3), Commit: 0b/16.6T (0%), Used: 0b]
  |   o- topology ............................................................................................... [OSDs: 32,MONs: 3]
  o- disks ........................................................................................................ [600G, Disks: 6]
  | o- rbd.disk_1 .................................................................................................. [disk_1 (100G)]
  | o- rbd.image0 .................................................................................................. [image0 (100G)]
  | o- rbd.image1 .................................................................................................. [image1 (100G)]
  | o- rbd.image2 .................................................................................................. [image2 (100G)]
  | o- rbd.image3 .................................................................................................. [image3 (100G)]
  | o- rbd.image5 .................................................................................................. [image5 (100G)]
  o- iscsi-target ..................................................................................................... [Targets: 1]
    o- iqn.2018-11.com.dameng.iscsi-gw:iscsi-gw ...................................................................... [Gateways: 3]
      o- gateways ............................................................................................ [Up: 3/3, Portals: 3]
      | o- ceph1 ................................................................................................. [10.5.5.201 (UP)]
      | o- ceph2 ................................................................................................. [10.5.5.202 (UP)]
      | o- ceph3 ................................................................................................. [10.5.5.203 (UP)]
      o- host-groups .................................................................................................. [Groups : 0]
      o- hosts .......................................................................................................... [Hosts: 4]
        o- iqn.2018-01.com.dameng:dm7-client ............................................... [LOGGED-IN, Auth: CHAP, Disks: 2(200G)]
        | o- lun 0 ................................................................................ [rbd.image0(100G), Owner: ceph1]
        | o- lun 1 ................................................................................ [rbd.disk_1(100G), Owner: ceph3]
        o- iqn.2018-12.com.test:test-linux ................................................. [LOGGED-IN, Auth: CHAP, Disks: 1(100G)]
        | o- lun 0 ................................................................................ [rbd.image1(100G), Owner: ceph3]
        o- iqn.2018-11.com.test:test-linux ............................................................ [Auth: CHAP, Disks: 1(100G)]
        | o- lun 0 ................................................................................ [rbd.image2(100G), Owner: ceph2]
        o- iqn.1998-01.com.vmware:5b8d6a11-cf6e-e6d0-afac-a4be2b25dc7d-2e91c819 ............ [LOGGED-IN, Auth: None, Disks: 2(200G)]
          o- lun 0 ................................................................................ [rbd.image3(100G), Owner: ceph1]
          o- lun 1 ................................................................................ [rbd.image5(100G), Owner: ceph2]
/> exit
[root@ceph1 log]#

**Comment by lxbsz** [comment]
> [root@ceph1 default_tg_pt_gp]# cat /sys/kernel/config/target/core/user_1/rbd.image1/alua/default_tg_pt_gp/alua_access_type
> Implicit and Explicit
> 

Not the default_tg_pt_gp, it should be XXXX_tg_pt_gp_ao alua group, due to your logs saying the ao alua group is not found.

The following is mine, NOTE, I am using the glfs, not rbd, so the names are different.
```
sh-4.2# cat /sys/kernel/config/target/core/user_0/blockvol_05de869110e7a93027aac6ffe191cb4e/alua/default_tg_pt_gp/alua_access_type 
Implicit and Explicit
sh-4.2# cat /sys/kernel/config/target/core/user_0/blockvol_05de869110e7a93027aac6ffe191cb4e/alua/glfs_tg_pt_gp_ao/alua_access_type 
Implicit
sh-4.2# cat /sys/kernel/config/target/core/user_0/blockvol_05de869110e7a93027aac6ffe191cb4e/alua/glfs_tg_pt_gp_ano/alua_access_type 
Implicit
sh-4.2# 

```

**Comment by zouyueming** [comment]
In this directory, I didn't find XXX_tg_pt_ao alua group as you mentioned.

[root@ceph1 alua]# ll /sys/kernel/config/target/core/user_0/rbd.image-0/alua/
总用量 0
drwxr-xr-x. 2 root root 0 11月 14 02:34 ao
drwxr-xr-x. 2 root root 0 11月 14 02:35 default_tg_pt_gp
drwxr-xr-x. 2 root root 0 11月 14 02:35 standby2
drwxr-xr-x. 2 root root 0 11月 14 02:35 standby3
[root@ceph1 alua]# cat ao/alua_access_type 
Implicit and Explicit
[root@ceph1 alua]# cat default_tg_pt_gp/alua_access_type 
Implicit and Explicit
[root@ceph1 alua]# cat standby2/alua_access_type 
Implicit and Explicit
[root@ceph1 alua]# cat standby3/alua_access_type 
Implicit and Explicit
[root@ceph1 alua]# 

 I don't know where the problem lies. All alua_access_type is implicit and explicit, what should I do？

**Comment by zouyueming** [comment]
@mikechristie 
i am using the ceph-iscsi-cli and ceph-iscsi-config 

[root@ceph1 alua]# yum list installed |grep ceph-iscsi
ceph-iscsi-cli.noarch 2.7-2.7.el7 @ceph-iscsi
ceph-iscsi-config.noarch 2.6-2.6.el7 @ceph-iscsi

i got it from  [http://mirrors.163.com/ceph](url)

Maybe I need to get them on github？
Which version did you solve this problem？

**Comment by mikechristie** [comment]
@zouyueming  Lol, I see you are the same person asking in the other issue I just closed :)

Your link above just points back to the tcmu-runner GH. If you are using the upstream GH code then you need this patch:

https://github.com/ceph/ceph-iscsi-config/commit/8d66492b8c7134fb37b72b5e8e77d7c8109220d9#diff-e7e42d0fe8d5b05a9d7d8cbc542ed013

which is in the upstream ceph-iscsi-config GH repo's master branch.

It is also in ceph builds on shaman:

https://shaman.ceph.com/repos/ceph-iscsi-config/

here is the current version:

https://5.chacra.ceph.com/r/ceph-iscsi-config/master/69f0229e68aa540bff39541abab58f62980ef5ef/centos/7/flavors/default/noarch/
