### ISSUE TITLE
Hi ,excuse me,I want to ask how tcmu-runner supports VAAI？

### ISSUE THREAD

**Issue by letterwuyu** [open-iscsi/tcmu-runner#387]

**Comment by mikechristie** [comment]
It does. You should use ceph 12.2.4, so you can take advantage of the offloaded commands.

**Comment by letterwuyu** [comment]
@mikechristie,  Thank you for your answer and great work.

**Comment by mikechristie** [comment]
Thanks.

Closing. Feel free to reopen if you have more questions.
