### ISSUE TITLE
Dynamic config reloading doesn't work when trying to comment the "loglevel=5" line out

### ISSUE THREAD

**Issue by lxbsz** [open-iscsi/tcmu-runner#397]
It should be set the loglevel back to INFO as default.

**Comment by lxbsz** [comment]
https://github.com/open-iscsi/tcmu-runner/issues/397

**Comment by lxbsz** [comment]
https://github.com/open-iscsi/tcmu-runner/pull/398

**Comment by mikechristie** [comment]
#398 is merged. Closing issue. Thanks.
