### ISSUE TITLE
running tcmu-runner

### ISSUE THREAD

**Issue by linyuan870** [open-iscsi/tcmu-runner#404]
I was just beginning to contact tcmu-runner and installed according to README.md;when I want to run tcmu-runner:
**[root@198 tcmu-runner]# tcmu-runner 
2018-04-23 22:18:58.952 14583 [INFO] dyn_config_start:416: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
2018-04-23 22:18:58.987 14583 [ERROR] set_genl_features:281: Could not set features. Error -10**

Using targetcli to view backstores does not appear like readme：
/backstores> ls
o- backstores .......................................................... [...]
  o- user:glfs .......................................... [Storage Objects: 0]
  o- user:qcow .......................................... [Storage Objects: 0]
  o- user:rbd ........................................... [Storage Objects: 0]
  o- user:file .......................................... [Storage Objects: 0]
  o- user:zbc ........................................... [Storage Objects: 0]

## But like this：
**/backstores> ls
o- backstores ....................................................................... [...]
  o- block ........................................................... [Storage Objects: 1]
  | o- lun0 .................................... [/dev/sdb1 (0 bytes) write-thru activated]
  |   o- alua ............................................................ [ALUA Groups: 1]
  |     o- default_tg_pt_gp ................................ [ALUA state: Active/optimized]
  o- fileio .......................................................... [Storage Objects: 0]
  o- pscsi ........................................................... [Storage Objects: 0]
  o- ramdisk ......................................................... [Storage Objects: 0]
/backstores>**

Readme said By default, tcmu-runner installs the file, zbc, glfs, qcow and rbd tcmu-runner handlers; I don't know where the problem is now, and hope someone can help me out.

**Comment by draghuram** [comment]
Hi,

It will help to provide some information regarding the test environment.
That said, you may need to copy the handlers to "/lib64/tcmu-runner"
directory for them to show up in targetcli. Look for "handler_*.so" in
tcmu-runner directory after build.

Also keep in mind that "targetcli" you are using may or may not work well
with tcmu devices. In my own experience, I had better luck with recent
kernel + targetcli-fb (as described in README).

Thanks,
Raghu

**Comment by mikechristie** [comment]
> targetcli-fb

Also make sure you are using rtslib-fb. You can get both from https://github.com/open-iscsi/.

**Comment by linyuan870** [comment]
@mikechristie @draghuram thanks,Can see user:rbd. . .
**o- / ..................................................................... [...]
  o- backstores .......................................................... [...]
  | o- block .............................................. [Storage Objects: 1]
  | | o- lun0 ..................... [/dev/sdb1 (0 bytes) write-thru deactivated]
  | |   o- alua ............................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ................... [ALUA state: Active/optimized]
  | o- fileio ............................................. [Storage Objects: 0]
  | o- pscsi .............................................. [Storage Objects: 0]
  | o- ramdisk ............................................ [Storage Objects: 0]
  | o- user:glfs .......................................... [Storage Objects: 0]
  | o- user:qcow .......................................... [Storage Objects: 0]
  | o- user:rbd ........................................... [Storage Objects: 1]
  | | o- rbd0 ................................... [pool/rbd1 (1.0GiB) activated]
  | |   o- alua ............................................... [ALUA Groups: 0]
  | o- user:zbc ........................................... [Storage Objects: 0]
  o- iscsi ........................................................ [Targets: 1]
  | o- iqn.2003-01.org.linux-iscsi.198.x8664:sn.226f01c32bd5 ......... [TPGs: 1]
  |   o- tpg1 ........................................... [no-gen-acls, no-auth]
  |     o- acls ...................................................... [ACLs: 1]
  |     | o- iqn.2003-01.org.linux-iscsi.198.x8664:sn.226f01c32bd5:client  [Mapped LUNs: 1]
  |     |   o- mapped_lun0 ............................... [lun0 user/rbd0 (rw)]
  |     o- luns ...................................................... [LUNs: 1]
  |     | o- lun0 ........................................... [user/rbd0 (None)]
  |     o- portals ................................................ [Portals: 1]
  |       o- xx.xx.xx.xx:3260 ........................................... [OK]
  o- loopback ..................................................... [Targets: 0]**
But it looks like I have a new problem. I created an rbd0 in user:rbd and then created iqn, lun0 in iscsi. The iscsi client can also discover this iqn and the login is successful; however, it is not possible to mount rbd0 in user:rbd on the client.
I see o- lun0 ........................................... [ User/rbd0 (None)]. After user/rbd0 does not know why is none.
Or is the rbd0 created by user:rbd need to be mounted on the client and need additional operations?

**Comment by lxbsz** [comment]
| | o- rbd0 ................................... [pool/rbd1 (1.0GiB) activated]
| | o- alua ............................................... [ALUA Groups: 0]

It may due to your alua/ without any alua entity.
It should something like:

  | o- user:glfs .............................................................................................. [Storage Objects: 4]
  | | o- block01 ........................ [dht0@192.168.195.134/block-store/47b316eb-7066-4e2b-9cc9-009e254d42a2 (1.0GiB) activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 2]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | |   o- glfs_tg_pt_gp .......................................................................... [ALUA state: Active/optimized]

What's you kernel version ?

Or could you provide the tcmu-runner or kernel's logs when you are trying to login or doing the mounting  ? Any errors/warning ？

**Comment by linyuan870** [comment]
@lxbsz thanks,
Linux 198 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**[root@198 tcmu-runner]# tcmu-runner --handler-path /usr/local/lib64/tcmu-runner
2018-04-24 20:19:32.142 15900 [INFO] dyn_config_start:416: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
2018-04-24 20:19:32.181 15900 [ERROR] set_genl_features:281: Could not set features. Error -10
2018-04-24 20:19:32.182 15900 [WARN] tcmu_block_device:395 rbd/rbd0: Kernel does not support the block_dev action.
2018-04-24 20:19:32.182 15900 [WARN] timer_check_and_set_def:391 rbd/rbd0: osd op timeout ((null)) must be larger than osd heartbeat grace (20) + interval (6)!
2018-04-24 20:19:32.182 15900 [WARN] timer_check_and_set_def:410 rbd/rbd0: Will set the osd op timeout to 31 instead!
no monitors specified to connect to.
2018-04-24 20:19:32.199 15900 [ERROR] tcmu_rbd_image_open:447 rbd/rbd0: Could not connect to cluster. (Err -2)
2018-04-24 20:19:37.202 15900 [ERROR] add_device:568: handler open failed for uio0
2018-04-24 20:19:37.202 15900 [WARN] tcmu_unblock_device:418 rbd/rbd0: Kernel does not support the block_dev action.**

Before I created a lun0 in the backstores/block that there alua, then I successfully mounted on the client.
I just created a user:rbd on the readme;
I saw some needs on the Internet like this: rbd create ceph-client1-rbd1 --size 10240;rbd map...
The rbd0 path I created is pool/rbd1. Is it something I need to map this rbd to something like /dev/sdc so that the client can mount this /dev/sdc?

**Comment by lxbsz** [comment]
2018-04-24 20:19:32.199 15900 [ERROR] tcmu_rbd_image_open:447 rbd/rbd0: Could not connect to cluster. (Err -2)
2018-04-24 20:19:37.202 15900 [ERROR] add_device:568: handler open failed for uio0

Have you resolved this errors ?

**Comment by linyuan870** [comment]
@lxbsz 
Sorry, no. I do not know how to solve this problem.
I now want to simply run the tcmu-runner example, I did not deploy the cluster. I see that there are ceph and gluster options on the readme. What do I need to do now to mount?

**Comment by linyuan870** [comment]
@lxbsz 
If I want to create user:glfs like the one you give, do I need to choose gluster?

**Comment by linyuan870** [comment]
@lxbsz 
I git clone gluster/gluster-block
[root@198 sysconfig]# systemctl restart gluster-blockd
Failed to restart gluster-blockd.service: Unit not found.

**Comment by lxbsz** [comment]
NO, if so you no need to install gluster or ceph, you can just use the file_example handler to have a try.

**Comment by linyuan870** [comment]
@lxbsz 
How to use file_example? Can also create user:rbd or user:glfs and mount it?

**Comment by lxbsz** [comment]
Make sure /lib64/tcmu-runner/ has the handler_file.so handler, or you can just copy it there:
    
    [root@gblock2 rhel7]# ls /lib64/tcmu-runner/
    handler_file_optical.so  handler_file.so  handler_file_zbc.so  handler_glfs.so  handler_qcow.so  handler_rbd.so  libtcmu.so
    [root@gblock2 rhel7]#

    $ targetcli /backstores/user:file create myfile 1G myfile
    $ targetcli ls
    ....
      | o- user:file .............................................................................................. [Storage Objects: 1]
      | | o- myfile ...................................................................................... [myfile (1.0GiB) deactivated]
      | |   o- alua ................................................................................................... [ALUA Groups: 1]
      | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]

Then create the iscsi LUN as needed.

**Comment by linyuan870** [comment]
@lxbsz ,thanks a lot.
$ targetcli /backstores/user:file create myfile 1G myfile
Is the second myfile a real file (img) or /dev/sdb?

**Comment by linyuan870** [comment]
@lxbsz 
After luns was created fileio appeared alua
**o- / ..................................................................... [...]
  o- backstores .......................................................... [...]
  | o- block .............................................. [Storage Objects: 0]
  | o- fileio ............................................. [Storage Objects: 1]
  | | o- myfile ........................ [myfile (0 bytes) write-thru activated]
  | |   o- alua ............................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ................... [ALUA state: Active/optimized]
  | o- pscsi .............................................. [Storage Objects: 0]
  | o- ramdisk ............................................ [Storage Objects: 0]
  | o- user:fbo ........................................... [Storage Objects: 0]
  | o- user:file .......................................... [Storage Objects: 1]
  | | o- myfile .................................. [myfile (2.0GiB) deactivated]
  | |   o- alua ............................................... [ALUA Groups: 0]
  | o- user:glfs .......................................... [Storage Objects: 0]
  | o- user:qcow .......................................... [Storage Objects: 0]
  | o- user:rbd ........................................... [Storage Objects: 0]
  | o- user:zbc ........................................... [Storage Objects: 0]
  o- iscsi ........................................................ [Targets: 1]
  | o- iqn.2003-01.org.linux-iscsi.198.x8664:sn.2247f71c798c ......... [TPGs: 1]
  |   o- tpg1 ........................................... [no-gen-acls, no-auth]
  |     o- acls ...................................................... [ACLs: 1]
  |     | o- iqn.2003-01.org.linux-iscsi.198.x8664:sn.2247f71c798c:client  [Mapped LUNs: 1]
  |     |   o- mapped_lun0 ........................... [lun0 fileio/myfile (rw)]
  |     o- luns ...................................................... [LUNs: 1]
  |     | o- lun0 .................. [fileio/myfile (myfile) (default_tg_pt_gp)]
  |     o- portals ................................................ [Portals: 1]
  |       o- 192.168.2.151:3260 ........................................... [OK]
  o- loopback ..................................................... [Targets: 0]**
**Clients：**
[cp@localhost usr]$ lsscsi
[2:0:0:0]    disk    ATA      VBOX HARDDISK    1.0   /dev/sda 
[4:0:0:0]    disk    ATA      VBOX HARDDISK    1.0   /dev/sdb 
[21:0:0:0]   disk    LIO-ORG  FILEIO                4.0   /dev/sdc 

**[cp@localhost usr]$ sudo mount /dev/sdc /home/cp/mountdir
mount: you must specify the filesystem type
[cp@localhost usr]$ sudo mkfs.ext4 /dev/sdc
mke2fs 1.41.12 (17-May-2010)
/dev/sdc is entire device, not just one partition!
Proceed anyway? (y,n) y
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.**
Is it possible that myfile created in user:file cannot be formatted and mounted?

**Comment by lxbsz** [comment]
@linyuan870 

From you logs, it seems work for you, right ?

Yeah, it possible, if there has something wrong with your configuration or something others.

**Comment by linyuan870** [comment]
@lxbsz thanks very much,
It looks like there is only one last step left.
Based on your experience.Whether the error is on the server or the client？

**Comment by lxbsz** [comment]
@linyuan870 Both sides are possible.

**Comment by linyuan870** [comment]
@lxbsz， OK
Let me see for myself where the problem lies. Thank you very much for spending so much time.

**Comment by draghuram** [comment]
@liny You need to create the backstore for file in a certain way. One
required parameter is "size". Here is one example:

"/backstores/user:file create cfgstring=//tmp/testfile name=test
size=1057964544"

**Comment by linyuan870** [comment]
@draghuram thanks,
But it seems to be the same
$ targetcli /backstores/user:file create myfile 1G myfile

client:
**[cp@localhost tmp]$ lsscsi
[2:0:0:0]    disk    ATA      VBOX HARDDISK    1.0   /dev/sda 
[4:0:0:0]    disk    ATA      VBOX HARDDISK    1.0   /dev/sdb 
[23:0:0:0]   disk    LIO-ORG  FILEIO           4.0   /dev/sdc** 

I am on the server side，view to testfile：
**[root@198 tmp]# ll -t
total 20
-rw-------. 1 root root    0 Apr 25 05:49 testfile**

I found | | o- test .......................... [/tmp/testfile (1009.0MiB) deactivated
**/> ls
o- / ..................................................................... [...]
  o- backstores .......................................................... [...]
  | o- block .............................................. [Storage Objects: 0]
  | o- fileio ............................................. [Storage Objects: 1]
  | | o- tmp-testfile ........... [/tmp/testfile (0 bytes) write-thru activated]
  | |   o- alua ............................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ................... [ALUA state: Active/optimized]
  | o- pscsi .............................................. [Storage Objects: 0]
  | o- ramdisk ............................................ [Storage Objects: 0]
  | o- user:fbo ........................................... [Storage Objects: 0]
  | o- user:file .......................................... [Storage Objects: 1]
  | | o- test .......................... [/tmp/testfile (1009.0MiB) deactivated]
  | |   o- alua ............................................... [ALUA Groups: 0]
  | o- user:glfs .......................................... [Storage Objects: 0]**

**Comment by mikechristie** [comment]
handler_file just does read()/writes() to any old file like /home/mikechristie/myfile. You do not need to do anything special. It works just like lio's target_core_file backend.

**Comment by linyuan870** [comment]
@mikechristie thanks,
I think I shouldn't say it clearly. I wanted to be able to mount a cluster file system like gluster on the client (like gluster-block). Then this cluster file system is its own.

**Comment by linyuan870** [comment]
@mikechristie 
Not a simple example of running.

**Comment by draghuram** [comment]
Hi, I am not entirely sure if I understand your question completely but I
will take a stab at it any way. With tcmu-runner, you can implement LUNs
that can act as devices. File systems are at a different level so if you
want to implement a file system, I don't think that can be done using TCMU
plugin.

Thanks,
Raghu

**Comment by linyuan870** [comment]
@draghuram 
Such as using targetcli cd backstores, can find my implementation of user:myfile. After a series of operations, the client mounts my cluster storage.

**Comment by linyuan870** [comment]
@mikechristie Hi
If I want to write a makefile to compile tcmu-runner through g++, will the changes work?

**Comment by mikechristie** [comment]
I do not know enough about g++. I have no idea.

**Comment by linyuan870** [comment]
@mikechristie OK,thanks
