### ISSUE TITLE
Another TCMU library - libtcmu2

### ISSUE THREAD

**Issue by baihuahua** [open-iscsi/tcmu-runner#412]
Here is another userspace TCMU library to help write applications to handle TCMU devices. It's named [libtcmu2](https://github.com/baihuahua/libtcmu2/tree/new-model) to distinguish it from the libtcmu/tcmulib in tcmu-runner. The initial motivation of this new library is to resolve license incompatibility between libtcmu and other applications. It also uses a new model to handle TCMU devices create/removal management under Mike's advice so we can drop netlink processes and simplify TCMU handling to avoid potential bugs. This is an initial version at present and has been tested with qemu-tcmu.

This new library also needs some targetcli-fb changes. They are [here.](https://github.com/baihuahua/targetcli-fb/tree/libtcmu2)

Hope this new library could be hosted under [open-iscsi](https://github.com/open-iscsi) as a new project so other applications can link to it easily and it can also keep in sync with libtcmu/tcmu-runner.

**Comment by lxbsz** [comment]
Hey Mike,

How could we push this further? Since process of changing License is blocked for a long time.

**Comment by mikechristie** [comment]
I think I am blocking it by accident :)

I was just going to start to port tcmu-runner to it to verify it works for that daemon and then confirm with Chis and Andy they are ok with adding it under open-iscsi. I do not think they will have a issue with the latter, so it is really just on me porting it to make sure it is ok.

We just wrapped up development on a release so I will try to get it done this week or by next week.

**Comment by mikechristie** [comment]
Oh yeah, just to make sure we are talking about the same thing. We are only talking about merging the libiscsi2 referenced in this issue right?

You saw me ping the lawyers the other day and I never got a response, so I think we can just say forget that for now. If/when we get that settled we can move/port any old libtcmu/runner code over to libiscsi2 if needed. However, we always just rewrite it.

**Comment by lxbsz** [comment]
Yeah, I meant both.

I have well received that mails and it seems stuck. So let's push the libiscsi2 first and then we will engage in making qemu-tcmu productable as soon as possible.

Thanks,

**Comment by mikechristie** [comment]
It looks like the relicense will be no problem. Everyone has agreed. We are just waiting on one person and we can just rewrite their code if we never hear back since it is not too much to do.

PR is here:

https://github.com/open-iscsi/tcmu-runner/pull/425

We should then just readd the stable API we broke last release when we thought there were no outside users :)
