### ISSUE TITLE
Create rbd target with targetcli on readme

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#422]
Having such a description in readme.md puzzled me:
**************************************************** 
4.'cd' to the handler you want to setup:
/backstores> cd user:rbd

/backstores/user:rbd> create cfgstring=pool/rbd1;osd_op_timeout=30 name=rbd0 size=1G 
Created user-backed storage object rbd0 size 1073741824.

Note that the cfgstring is handler specific. The format is:

rbd: /pool_name/image_name[;osd_op_timeout=N;conf=N;id=N] (osd_op_timeout is optional and N is in seconds) (conf is optional and N is the path to the conf file) (id is optional and N is the id to connect to the cluster as)
**************************************************** 
In this command line：
/backstores/user:rbd> create cfgstring=pool/rbd1;osd_op_timeout=30 name=rbd0 size=1G
 Created user-backed storage object rbd0 size 1073741824.

Why do i create a rbd target by targetcli need to specify rbd name twice？
If I have created rbd1 in the ceph pool, is the result of this command that to create a rbd0 with a size of 1G in rbd1？
My idea is that the create command should create a rbd0 directly in the pool and mount it as target. I would like to know what role rbd1 has in the example, thanks.

**Comment by mikechristie** [comment]
The cfgstring format is pool_name/image_name;other_settings.

The pool_name is the name of a existing pool. The image_name is the name of a existing image. So have to have created these with rbd/rados commands already. They are the values you see when you run commands like "rbd ls".

The name=some_name is just the LIO/targetcli name for the backing device. It can be anything. It just the name of the LIO/targetcli object and is only used by them to reference the object.

For ceph you should use ceph-iscsi-cli http://github.com/ceph/ceph-iscsi-cli. It will handle these details for you btw.

**Comment by mikechristie** [comment]
The image must be created before you run the targetcli command. targetcli/tcmu does not create the image for you. It only tries to open an existing image.

**Comment by NUABO** [comment]
hi @mikechristie  Does that mean  “size=1G” is the target size instead of image size?  thank you very much for your help

**Comment by mikechristie** [comment]
> hi @mikechristie Does that mean “size=1G” is the target size instead of image size? thank you very much for your help

For rbd, the size value passed into the targetlci create create command is both the size exported by the target for LUN's size and it also has to match the image's size. See the call to tcmu_rbd_check_image_size in tcmu-runner/rbd.c for details.
