### ISSUE TITLE
Which version of the kernel is best for tcmu use

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#438]
I compile and install tcmu on centos 7.2 but the service fails to start.
Replace the centos7.2 kernel with the default kernel of centos7.3, 
the target_core_user module can be loaded.
I want to know which of the lowest available kernel versions is,
and which kernel version is recommended.
I wish to use target_core_user.ko and tcmu stably.
thanks

**Comment by NUABO** [comment]
Can I use the target_core_user driver for the centos7.2 default kernel 3.10.0-327.el7.x86_64 ?

**Comment by NUABO** [comment]
I have replaced multiple versions of the kernel and still can't start the tcmu service

[root@node ~]# uname -r
3.10.0-862.3.3.el7.x86_64
[root@node ~]# systemctl daemon-reload
[root@node ~]# systemctl restart tcmu-runner 
Job for tcmu-runner.service failed because the control process exited with error code. See "systemctl status tcmu-runner.service" and "journalctl -xe" for details.
[root@node ~]# systemctl status tcmu-runner.servic
● tcmu-runner.servic.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[root@node ~]# systemctl status tcmu-runner.service
● tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-06-28 18:41:32 CST; 18s ago
  Process: 1314 ExecStart=/usr/bin/tcmu-runner (code=exited, status=203/EXEC)
 Main PID: 1314 (code=exited, status=203/EXEC)
Jun 28 18:41:32 node systemd[1]: Starting LIO Userspace-passthrough daemon...
Jun 28 18:41:32 node systemd[1]: tcmu-runner.service: main process exited, code=exited, status=203/EXEC
Jun 28 18:41:32 node systemd[1]: Failed to start LIO Userspace-passthrough daemon.
Jun 28 18:41:32 node systemd[1]: Unit tcmu-runner.service entered failed state.
Jun 28 18:41:32 node systemd[1]: tcmu-runner.service failed.

**Comment by mikechristie** [comment]
I think you need a minimum of the RHEL 7.3 kernel. It depends on what you want to do though.

If you are using gluster or ceph then you need newer kernels. If you just want to use handler_file then 7.3 would be fine.

Probably using the upstream kernel is best though. Do you need to use a distro kernel?

**Comment by NUABO** [comment]
hi @mikechristie 
    I'm going to use the distribution kernel，I know that this kernel is usually the lower version.
    In this case, is the stability of target_core_user.ko guaranteed? Whether it will affect performance,
and which version of the kernel are you using.
    I would like to use it in distributed storage such as gluster, future plans are used on other storage.

**Comment by NUABO** [comment]
I am using the default kernel of centos7.3 (3.10.0-514.el7.x86_64) and the following error occurred
set_genl_features:281: Could not set features. Error -10

[root@node tcmu-runner]# ll /usr/local/lib64/tcmu-runner
total 60
-rwxr-xr-x. 1 root root 37827 Jun 29 18:08 handler_file_zbc.so

Details are as follows：
[root@node tcmu-runner]# systemctl status tcmu-runner 
● tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-06-29 18:14:52 CST; 14s ago
 Main PID: 2652 (tcmu-runner)
   CGroup: /system.slice/tcmu-runner.service
           └─2652 /usr/bin/tcmu-runner

Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.763 2652 [DEBUG] main:1058: handler path: /usr/local/lib64/tcmu-runner
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.764 2652 [DEBUG] load_our_module:529: Module 'target_core_user' is already loaded
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.764 2652 [DEBUG] main:1071: 2 runner handlers found
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.765 2652 [ERROR] set_genl_features:281: Could not set features. Error -10
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.767 2652 [INFO] dyn_config_start:416: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
Jun 29 18:14:52 node tcmu-runner[2652]: set_genl_features:281: Could not set features. Error -10
Jun 29 18:14:52 node tcmu-runner[2652]: dyn_config_start:416: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.770 2652 [DEBUG] dbus_bus_acquired:443: bus org.kernel.TCMUService1 acquired
Jun 29 18:14:52 node systemd[1]: Started LIO Userspace-passthrough daemon.
Jun 29 18:14:52 node tcmu-runner[2652]: 2018-06-29 18:14:52.776 2652 [DEBUG] dbus_name_acquired:459: name org.kernel.TCMUService1 acquired

**Comment by NUABO** [comment]
I found an explanation in the Version 1.3.0 release notes.
