### ISSUE TITLE
can tcmu be used on ubuntu systems

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#489]
hi, the kernel version of the ubuntu system is higher than the centos. Can tcmu be used on ubuntu systems? thanks

**Comment by bgly** [comment]
Tcmu has always worked for Ubuntu, it’s a matter of features that are supported based on the different kernel levels

**Comment by NUABO** [comment]
> Tcmu has always worked for Ubuntu, it’s a matter of features that are supported based on the different kernel levels

That's good, thanks
