### ISSUE TITLE
Whether to need to join the memory pool mechanism in the ceph plugin

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#524]
There are frequent malloc/free in the ceph plugin read and write process, which will cause memory fragmentation. Is it necessary to introduce a reliable memory pool?

**Comment by mikechristie** [comment]
It seems like it could be an issue. Have you done some traces and is it a problem? If so feel free to go for it.

There are a couple places in the kernel that could be an issue too.

**Comment by NUABO** [comment]
I plan to do some experiments 😃 , there is no clear idea yet.
