### ISSUE TITLE
Failed to create iSCSI target 

### ISSUE THREAD

**Issue by giftz** [open-iscsi/tcmu-runner#534]
## Environment
* OS release: CentOS Linux 7 (Core)  
* Kernel version: 3.10.0-957.el7.x86_64  
* Initiator and target are same machine  

## Device creation  
* Device type: Custom device type which is similar to TCMU-runner consumer.c  
```
static struct tcmulib_handler mc_handler = {
    .name = "Test handler",
    .subtype = "tst",
```
* Creation: Use configfs interface to create iscsi targets (see below commands)  

## Results  
* **[FAIL]** iscsiadm can discover and login to the new iSCSI target, but there is no block device created   
* **[OK]** Tried to create TCM loopback device instead of iSCSI target, the new block device can be created successfully

### iSCSI target creation
```
mkdir /sys/kernel/config/target/core/user_1/vol1
echo -n dev_size=104857600 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n hw_block_size=512 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n dev_config=tst/vol1 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n 1 > /sys/kernel/config/target/core/user_1/vol1/enable   << after this, the /dev/uio* can be seen

mkdir /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1
mkdir /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/lun/lun_0
ln -s /sys/kernel/config/target/core/user_1/vol1 /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/lun/lun_0/vol1
echo -n 1 > /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/enable
mkdir /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/np/<ip>:3260
mkdir /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/acls/<initiator string from /etc/iscsi/initiatorname.iscsi>

edit /etc/iscsi/iscsid.conf to set the userid and password to test/test

echo -n test > /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/acls/<initiator string from /etc/iscsi/initiatorname.iscsi>/auth/userid
echo -n test > /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/acls/<initiator string from /etc/iscsi/initiatorname.iscsi>/auth/password
echo -n 1 > /sys/kernel/config/target/iscsi/iqn.2019-01.com.xxx:vol1/tpgt_1/attrib/authentication
```

iSCSI target discovery and login:
```
iscsiadm -m discovery -t sendtargets -p <ip>
<ip>:3260,1 iqn.2019-01.xxx.<hostname>:vol1

iscsiadm -m node --login
Logging in to [iface: default, target: iqn.2019-01.com.xxx:vol1, portal: <ip>,3260] (multiple)
Login to [iface: default, target: iqn.2019-01.com.xxx:vol1, portal: <ip>,3260] successful.

```

However, there is no block device created from /dev/sdx, the /var/log/messages show:  
```
Jan 29 15:30:58 iscsid: Could not set session18 priority. READ/WRITE throughout and latency could be affected.
Jan 29 15:30:58 iscsid: Connection18:0 to [target: iqn.2019-01.com.xxx:vol1, portal: <ip>,3260] through [iface: default] is operational now

```

### TCM loop device

```
mkdir /sys/kernel/config/target/core/user_1/vol1
echo -n dev_size=104857600 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n hw_block_size=512 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n dev_config=tst/vol1 > /sys/kernel/config/target/core/user_1/vol1/control
echo -n 1 > /sys/kernel/config/target/core/user_1/vol1/enable   << after this, the /dev/uio* can be seen

mkdir /sys/kernel/config/target/loopback
mkdir /sys/kernel/config/target/loopback/naa.60014057f822d991
mkdir /sys/kernel/config/target/loopback/naa.60014057f822d991/tpgt_1
mkdir /sys/kernel/config/target/loopback/naa.60014057f822d991/tpgt_1/lun/lun_0
echo -n "naa.60014057f822d991" > /sys/kernel/config/target/loopback/naa.60014057f822d991/tpgt_1/nexus
ln -s /sys/kernel/config/target/core/user_1/vol1 tpgt_1/lun/lun_0/vol1

```
After this, the new block device is seen from lsblk:   
```
sdc               8:64   0    100M  0 disk
```

## Expectation/Question
* Why iSCSI target can not be created with TCMU? Is there any limitation on TCMU/TCMU-runner/kernel? Or there is something wrong with my procedures?  
* Anything else I can try?

**Comment by mikechristie** [comment]
I think the lun is not mapped to acl. It is only mapped to the tpg.

Please use targetcli too. This is not a lio support group, so knowing the manual setup commands is not something we specialize in.

**Comment by giftz** [comment]
## Update:  
Tried to use the TCMU-runner file_example.c handler, and use targetcli to config a new target, I was able to create the iSCSI target in this way, so it looks like the manual configfs command + TCMU runner is not working for iSCSI target (while it's working for TCM loopback device), not sure where is the problem, but I got the work around anyway.  

@mikechristie 
Thanks for the response, could you elaborate on 
>I think the lun is not mapped to acl. It is only mapped to the tpg.

**Comment by mikechristie** [comment]
> @mikechristie
> Thanks for the response, could you elaborate on
> 
> > I think the lun is not mapped to acl. It is only mapped to the tpg.

Did you create the lun dir in the initiator acl dir? For example:

[root@rh1 iqn.2005-03.com.ceph:ini1]# pwd
/sys/kernel/config/target/iscsi/iqn.1999-09.com.tcmu:alua/tpgt_1/acls/iqn.2005-03.com.ceph:ini1

[root@rh1 iqn.2005-03.com.ceph:ini1]# ls
attrib  auth  cmdsn_depth  fabric_statistics  info  lun_0  param  tag

[root@rh1 iqn.2005-03.com.ceph:ini1]# cd lun_0/
[root@rh1 lun_0]# ls
06b3a2f8b4  statistics  write_protect

In targetcli it would look like:

> 
>   o- iscsi ........................................................ [Targets: 1]
>   | o- iqn.1999-09.com.tcmu:alua ..................................... [TPGs: 1]
>   |   o- tpg1 ................................. [gen-acls, tpg-auth, 1-way auth]
>   |     o- acls ...................................................... [ACLs: 1]
>   |     | o- iqn.2005-03.com.ceph:ini1 .......... [auth via tpg, Mapped LUNs: 1]
>   |     |   o- mapped_lun0 ............................. [lun0 fileio/lun0 (rw)]
>   |     o- luns ...................................................... [LUNs: 1]
>   |     | o- lun0 ........... [fileio/lun0 (/work/luns/lun0) (default_tg_pt_gp)]
>   |     o- portals ................................................ [Portals: 1]
>   |       o- 192.168.32.101:3260 .......................................... [OK]
>

**Comment by giftz** [comment]
@mikechristie ,
Good point! After I added the creation of acls/\<initiator\>/lun_0 and link to tpgt lun0 path, the iSCSI target is successfully created with configfs commands.    

Thanks for the help. 👍
