### ISSUE TITLE
Man page should be installed

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/tcmu-runner#54]
The CMakeList.txt file does not install the man page, but it should.

Simply adding this, for example at the end of the CMakeList.txt file, does the trick:

------------------------------------------------------------------------------------------
```
...
install(FILES tcmu-runner.8
    DESTINATION ${CMAKE_INSTALL_PREFIX}/share/man/man8)
```
------------------------------------------------------------------------------------------

**Comment by gonzoleeman** [comment]
Note: I can easily submit a pull request for this, if you wish, but it's such a small change I thought perhaps it was overkill.

**Comment by agrover** [comment]
yes please submit a PR, there's no change too small and it's actually less work to pull in for me.

(Sorry for the delay in response)

**Comment by gonzoleeman** [comment]
No problem about delay. :) But let me know next time if you are busy and I can cover. Also, I created the aforementioned pull request.

**Comment by agrover** [comment]
fixed now, closing
