### ISSUE TITLE
tcmu-runner crashed by SEGV signal

### ISSUE THREAD

**Issue by AresChen1** [open-iscsi/tcmu-runner#552]
Env:
Ceph Cluster on centos 7.5.1804, kernel 3.10.0-957.1.3.el7.x86_64:
**cluster:**
    id:     f2f26e90-e9a6-4799-ac0e-2b7d9c0e083e
    health: HEALTH_OK
 
  services:
    mon:         3 daemons, quorum node0010,node0011,node0012
    mgr:         node0011(active), standbys: node0012, node0010
    osd:         5 osds: 5 up, 5 in
    tcmu-runner: 3 daemons active
 
  data:
    pools:   2 pools, 128 pgs
    objects: 1.03 k objects, 3.8 GiB
    usage:   15 GiB used, 33 GiB / 48 GiB avail
    pgs:     128 active+clean

**tcmu-runner version: 1.4.0**
**Targets Gateways Info(On these same ceph cluster nodes):**
   iscsi-targets ............................................................................... [DiscoveryAuth: None, Targets: 1]
    o- iqn.2019-05.com.test.iscsi-gw:008083de3f7f898b ............................................................. [Gateways: 3]
      o- disks .......................................................................................................... [Disks: 1]
      | o- testpool/testimage .................................................................................... [Owner: node0012]
      o- gateways ............................................................................................ [Up: 3/3, Portals: 3]
      | o- node0010 ............................................................................................. [10.0.100.10 (UP)]
      | o- node0011 ............................................................................................. [10.0.100.11 (UP)]
      | o- node0012 ............................................................................................. [10.0.100.12 (UP)]
      o- host-groups .................................................................................................. [Groups : 0]
      o- hosts ............................................................................................... [Hosts: 1: Auth: ACL]
        o- iqn.1994-05.com.redhat:a92e9f6e6e80 .............................................. [LOGGED-IN, Auth: None, Disks: 1(20G)]
          o- lun 0 ...................................................................... [testpool/testimage(20G), Owner: node0012]

**Test procedure:**
1, create a replicated pool that named "testpool" and set this pool quota to 4GB.
2, create a 20GB rbd image that named "testimage" in "testpool".
3, add "testpool/testimage" into "iqn.1994-05.com.redhat:a92e9f6e6e80" initiator mapped luns.
4, Use "iscsiadm" to login the "iqn.2019-05.com.test.iscsi-gw:008083de3f7f898b" target.
5, Use "multipath -ll" list belows info:
    

> mpathc (36001405edc56915081c40be8693e9b3e) dm-2 LIO-ORG ,TCMU device     
>     size=20G features='1 queue_if_no_path' hwhandler='1 alua' wp=rw
>       |-+- policy='queue-length 0' prio=10 status=enabled
>           | `- 5:0:0:0 sdd 8:48 active ready running
>       |-+- policy='queue-length 0' prio=10 status=enabled
>           | `- 4:0:0:0 sdb 8:16 active ready running
>       |-+- policy='queue-length 0' prio=50 status=active
>         `- 3:0:0:0 sdc 8:32 active ready running

    

> **/etc/multipath.conf config info:**
>     device {
>                 vendor                 "LIO-ORG"
>                 hardware_handler       "1 alua"
>                 path_grouping_policy   "failover"
>                 path_selector          "queue-length 0"
>                 failback               60
>                 path_checker           tur
>                 prio                   alua
>                 prio_args              exclusive_pref_bit
>                 fast_io_fail_tmo       25
>                 no_path_retry          queue
>         }
6, Use "fio" to write on "mapthc", when "testpool"'s quota is full. The librbd will return "-110" to "tcmu-runner", and then multipath will switch the path to other gateway. But it still get "-110" error code. Wait some minutes, the tcmu-runner process crashed by SEGV signal on the path that will be switched.

 **The list below is call trace:**

> #0  0x00007f2b7ad978fb in librbd::is_exclusive_lock_owner(librbd::ImageCtx*, bool*) () at /lib64/librbd.so.1
> #1  0x00007f2b7ad4f358 in rbd_is_exclusive_lock_owner () at /lib64/librbd.so.1
> #2  0x00007f2b7b28cf80 in tcmu_rbd_has_lock (dev=0x1d28e00) at /usr/src/debug/tcmu-runner-1.4.0/rbd.c:513
> #3  0x00007f2b7b28d043 in tcmu_rbd_get_lock_state (dev=0x1d28e00) at /usr/src/debug/tcmu-runner-1.4.0/rbd.c:533
> #4  0x000000000040e424 in tcmu_update_dev_lock_state (dev=0x1d28e00) at /usr/src/debug/tcmu-runner-1.4.0/tcmur_device.c:427
> #5  0x000000000041009c in alua_sync_state (dev=0x1d28e00, group_list=0x7f2b457f9c50, enabled_group_id=3) at /usr/src/debug/tcmu-runner-1.4.0/alua.c:407
> #6  0x000000000041035d in tcmu_emulate_report_tgt_port_grps (dev=0x1d28e00, group_list=0x7f2b457f9c50, cmd=0x1e3a950) at /usr/src/debug/tcmu-runner-1.4.0/alua.c:489
> #7  0x000000000040c1b5 in handle_rtpg (dev=0x1d28e00, cmd=0x1e3a950) at /usr/src/debug/tcmu-runner-1.4.0/tcmur_cmd_handler.c:2169
> #8  0x000000000040c85d in handle_sync_cmd (dev=0x1d28e00, cmd=0x1e3a950) at /usr/src/debug/tcmu-runner-1.4.0/tcmur_cmd_handler.c:2390
> #9  0x000000000040cb8e in tcmur_generic_handle_cmd (dev=0x1d28e00, cmd=0x1e3a950) at /usr/src/debug/tcmu-runner-1.4.0/tcmur_cmd_handler.c:2507
> #10 0x00000000004121d7 in tcmur_cmdproc_thread (arg=0x1d28e00) at /usr/src/debug/tcmu-runner-1.4.0/main.c:632
> #11 0x00007f2b84de8dd5 in start_thread (arg=0x7f2b457fa700) at pthread_create.c:307
> #12 0x00007f2b842d0ead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
    
**Root cause:**
When switch to other path, it will reopen the rbd image again, but it will open failed because the pool's quota is full.When tcmu-runner get "INQUIRY" iscsi cmd, it will check the rbd image's lock state, but the rbd image state at "struct tcmu_device->hm_private" is a wild poiner. Because this pointer is freed in "tcmu_rbd_open:free_stat" branch.

**Comment by mikechristie** [comment]
Very nice debugging! Thanks for all the details and info. I think this is already fixed in 1.4.1:

https://github.com/open-iscsi/tcmu-runner/releases/tag/v1.4.1

**Comment by AresChen1** [comment]
> Very nice debugging! Thanks for all the details and info. I think this is already fixed in 1.4.1:
> 
> https://github.com/open-iscsi/tcmu-runner/releases/tag/v1.4.1

Hi Mike，can you list the commit id for me?Thanks a lot.

**Comment by mikechristie** [comment]
It came in this PR

https://github.com/open-iscsi/tcmu-runner/pull/525

Here is the specific patch:

https://github.com/open-iscsi/tcmu-runner/pull/525/commits/a320ef8b174d21085221044dcf1e0ae70fa18b1a

**Comment by AresChen1** [comment]
thanks a lot
