### ISSUE TITLE
No user:zbc found on Fedora release 30

### ISSUE THREAD

**Issue by wxucnexlabs** [open-iscsi/tcmu-runner#571]
Hi Guys,

I can't see the targetcli result as the readme shows,
should have user:xxx too,
but I only got:
[root@localhost ~]# targetcli 
targetcli shell version 2.1.fb49
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> ls
o- / .................................................................. [...]
  o- backstores ....................................................... [...]
  | o- block ........................................... [Storage Objects: 0]
  | o- fileio .......................................... [Storage Objects: 0]
  | o- pscsi ........................................... [Storage Objects: 0]
  | o- ramdisk ......................................... [Storage Objects: 0]
  o- iscsi ..................................................... [Targets: 0]
  o- loopback .................................................. [Targets: 0]
  o- vhost ..................................................... [Targets: 0]
/> exit

also when I run the tcmu-runner, it looks like stucked, no any message shows runing sign.

Here's steps:
1  cd extra/
2  ./install_dep.sh 
3  cd ..
4  cmake .
5  vim CMakeCache.txt 
6  make
7  make install

system information: 
[root@localhost ~]# cat /etc/redhat-release 
Fedora release 30 (Thirty)
[root@localhost ~]# uname -a                
Linux localhost.localdomain 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# 

Can you give me any clue?
Thanks

**Comment by wxucnexlabs** [comment]
it says
`[root@localhost tcmu-runner]# tcmu-runner 
tcmu-runner: error while loading shared libraries: libtcmu.so.2: cannot open shared object file: No such file or directory`

then I hardly fixed by "cp /usr/local/lib64/libtcmu* /usr/lib64/"

also got the same result with or without " --handler-path /usr/local/lib64/tcmu-runner/"

**Comment by mikechristie** [comment]
I'm not sure what you are reporting. It does not seem like a tcmu-runner issue.

You can control where the lib is installed with the -DCMAKE_INSTALL_PREFIX= option.

If you are installing to something that is not setup in ld.so.conf then you need to update that or install to a path that is setup.

The --handler-path only controls where the handlers (handler_*.so) are.

It seems for how your ld.so.conf is setup you want to do

cmake -DCMAKE_INSTALL_PREFIX=/usr

**Comment by wxucnexlabs** [comment]
Hi Mike,

Thanks for the explation regarding the path installed
There's one more thing I was wondering is the result of run the tcmu-running command

I'm expecting something like this:

`[root@LabTest]# tcmu-runner
log file path now is '/var/log/tcmu-runner.log'
Starting...
[root@LabTest]# `

or

`[root@198 tcmu-runner]# tcmu-runner
2018-04-23 22:18:58.952 14583 [INFO] dyn_config_start:416: Inotify is watching "/etc/tcmu/tcmu.conf", wd: 1, mask: IN_ALL_EVENTS
2018-04-23 22:18:58.987 14583 [ERROR] set_genl_features:281: Could not set features. Error -10`

but what I've got is:
`[root@localhost tcmu-runner]# tcmu-runner 

`
do you have any further idea?

**Comment by mikechristie** [comment]
We have changed the logging a couple times, so some messages might be getting directed to different places than other versions or they might be dropped. For example, we started directing some messages to only the log file /var/log/tcmu-runner.log or /var/log/messages (wherever syslog goes for your). Some still go to stderr, and some still go to multiple places.

For the set_genl_features error, you might not be seeing it anymore if you have updated your kernel. That message normally means tcmu-runner supports features your kernel did not.

**Comment by wxucnexlabs** [comment]
Hi 

there should be some print output, right?
instead of it appears to stuck right now.

**Comment by mikechristie** [comment]
Yes. Run it with debugging on and/or in strace. Check the log files, etc.

**Comment by zjs1224522500** [comment]
Hi Guys:
    I met a similar problem.In my targetcli, I only got:
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:fbo ............................................................................................... [Storage Objects: 0]
  | o- user:rbd ............................................................................................... [Storage Objects: 0]
  | o- user:zbc ............................................................................................... [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 0]
  o- loopback ......................................................................................................... [Targets: 0]
  o- srpt ............................................................................................................. [Targets: 0]

  I don't know why there is no user:file.
  I'm sure that I take steps as readme.md described.
  Could anyone please give me some clue?
  Thanks a lot!

**Comment by mikechristie** [comment]
@zjs1224522500 

Your problem is completely different. This issue is for when no tcmu handler shows up.

It looks like your distro does not package the file handler or if you built it is yourself you did not install it. It is just an example handler, so by default it does not install with "make install". You have to copy it to your handler directory and then start tcmu-runner.

**Comment by zjs1224522500** [comment]
@mikechristie Thank you firstly.
But I can't find the handler directory. Is there any default path for it? 

After "make install" operation:
There exist "handler_file.so" in tcmu-runner directory.And I am not sure that if I need to eidt the config in CMakeLists.txt. I used the default configuration.

And my system info:
[root@localhost /]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core) 
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mikechristie** [comment]
Closing for now. Have not heard back in a month. Reopen if you get more log output.
