### ISSUE TITLE
Callers of tcmu_iovec_seek() not applying return value

### ISSUE THREAD

**Issue by DavidButterfield** [open-iscsi/tcmu-runner#573]
Code in qcow_read() intends to advance partway through an iovec after a partial preadv().  It  
calls tcmu_iovec_seek(iovec, nbytes), which advances through enough iovec entries to consume
nbytes, fixes up the base and len of the ending entry, and returns the number of entries it
advanced over.

Caller is expected to adjust his iovec pointer and iov_cnt by the number of entries advanced
over by tcmu_iovec_seek(), before trying to continue the read.

But I don't see logic to do that in qcow_read() or qcow_write().  Also file_example.c and 
file_optical.c appear similar.

I don't know about the usage in tcmu_cmd_seek(), but at a glance it seems suspicious because it
only reduces count, doesn't increase a pointer (and I'm not imagining why that would be useful)

That's my analysis, but don't believe too easily because I only happened to notice it reading
the code.  I haven't tried to trigger it, or even compile the suggested changes attached.

It would seem fairly heinous, except I suppose the preadv() must be pretty unlikely to return
anything other than zero or the full number of bytes requested.

[iovec_advance.txt](https://github.com/open-iscsi/tcmu-runner/files/3385151/iovec_advance.txt)

**Comment by lxbsz** [comment]
@DavidButterfield 

Thanks for using and your good question about this :-)

```
142 size_t tcmu_iovec_seek(struct iovec *iovec, size_t count)
143 {  
144     size_t consumed = 0;
145    
146     while (count) {
147         if (count >= iovec->iov_len) {      
148             count -= iovec->iov_len;            
149             iovec->iov_len = 0;
150             iovec++;
151             consumed++;        
152         } else {
153             iovec->iov_base += count;           
154             iovec->iov_len -= count;            
155             count = 0;
156         }
157     }
158                                
159     return consumed;
160 }
```

Have you hit any problem with the current logic ?

Did you see Line#149 ? That means it will disable the first iovecs which have been filled with the data readed this time and then just set these iovecs' length to 0, for next preadv it will skip them.

But your changes here also should work as expected.

Thanks.
BRs

**Comment by DavidButterfield** [comment]
Aha, I see!  Thanks for that explanation.  Now I think this is not a bug.
(Maybe a code comment would be good.)

If this pread() can result often in a short read, the changes might still
be appropriate for optimization purposes.  Otherwise it doesn't matter.

On 7/12/19 12:49 AM, Xiubo Li wrote:
> @DavidButterfield <https://github.com/DavidButterfield>
> 
> Thanks for using and your good question about this :-)
> Have you hit any problem with the current logic ?
> 
> Did you see Line#149 ? That means it will disable the first iovecs which have been filled with the data readed this time and then just set these iovecs' length to 0, for next preadv it will skip them.

142 size_t tcmu_iovec_seek(struct iovec *iovec, size_t count)
143 {  
144     size_t consumed = 0;
145    
146     while (count) {
147         if (count >= iovec->iov_len) {      
148             count -= iovec->iov_len;            
149             iovec->iov_len = 0;
150             iovec++;
151             consumed++;        
152         } else {
153             iovec->iov_base += count;           
154             iovec->iov_len -= count;            
155             count = 0;
156         }
157     }
158                                
159     return consumed;
160 }

**Comment by mikechristie** [comment]
Closing this for now. I do not see short read/writes ever. It can happen, but right now it hasn't been worth it to add any changes for it since we can't test if it makes any difference since it is so rare.

If you come up with a patch that makes the code better in general or do have a test that shows it makes a difference just open a PR.
