### ISSUE TITLE
No user:file found on centos7.4

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/tcmu-runner#574]
Hi Guys:
In my targetcli, I only got:
o- / ......................................................................................................................... [...]
o- backstores .............................................................................................................. [...]
| o- block .................................................................................................. [Storage Objects: 0]
| o- fileio ................................................................................................. [Storage Objects: 0]
| o- pscsi .................................................................................................. [Storage Objects: 0]
| o- ramdisk ................................................................................................ [Storage Objects: 0]
| o- user:fbo ............................................................................................... [Storage Objects: 0]
| o- user:rbd ............................................................................................... [Storage Objects: 0]
| o- user:zbc ............................................................................................... [Storage Objects: 0]
o- iscsi ............................................................................................................ [Targets: 0]
o- loopback ......................................................................................................... [Targets: 0]
o- srpt ............................................................................................................. [Targets: 0]

I don't know why there is no user:file.
I'm sure that I take steps as readme.md described.
And thanks mike for giving me some clues. [issues 571](https://github.com/open-iscsi/tcmu-runner/issues/571#issuecomment-510727821)
But I didn't find the handler directory. I have no idea about how to add user:file to the targetcli.

After "make install" operation:
There exist "handler_file.so" in tcmu-runner directory.And I am not sure that if I need to eidt the config in CMakeLists.txt. I used the default configuration.

And my system info:
[root@localhost /]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Could anyone please give me some instructions?

Thanks a lot!
Best Regards!

**Comment by lxbsz** [comment]
@zjs1224522500 

As Mike said, the cmakefile won't install it as defualt.

The following should work for you:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0ddcdde..6dbae02 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -168,6 +168,7 @@ set_target_properties(handler_file
 target_include_directories(handler_file
   PUBLIC ${PROJECT_SOURCE_DIR}/ccan
   )
+install(TARGETS handler_file DESTINATION ${CMAKE_INSTALL_LIBDIR}/tcmu-runner)
 
 if (with-fbo)
        # Stuff for building the file optical handler

```

Thanks,
BRs

**Comment by zjs1224522500** [comment]
@lxbsz Thanks firstly!
Before solving the problem issued in this issue, I met another trouble.
When I run the ./tcmu-runner, the command line was like (pending):

[root@localhost tcmu-runner]# ./tcmu-runner 
log level now is DEBUG
Attempting to use '/var/log/tcmu-runner.log' as the log file path
log file path now is '/var/log/tcmu-runner.log'
Starting...

And I vi the log file in /var/log/tcmu-runner.log. There exist one error.

2019-07-14 21:22:06.479 15495 [DEBUG] load_our_module:537: Module 'target_core_user' is already loaded
2019-07-14 21:22:06.479 15495 [DEBUG] main:1106: handler path: /usr/lib64/tcmu-runner
2019-07-14 21:22:06.479 15495 [DEBUG] main:1112: blocking netlink
**2019-07-14 21:22:06.480 15495 [ERROR] tcmu_cfgfs_set_str:294: Kernel does not support configfs file /sys/module/target_core_user/parameters/block_netlink.**
2019-07-14 21:22:06.480 15495 [DEBUG] main:1115: blocking netlink done
2019-07-14 21:22:06.492 15495 [DEBUG] main:1133: 5 runner handlers found
2019-07-14 21:22:06.492 15495 [DEBUG] dyn_config_start:427: Inotify is watching "/etc/tcmu", wd: 1, mask: IN_MODIFY
2019-07-14 21:22:06.496 15495 [DEBUG] dbus_bus_acquired:450: bus org.kernel.TCMUService1 acquired
2019-07-14 21:22:06.497 15495 [DEBUG] dbus_name_acquired:466: name org.kernel.TCMUService1 acquired

After I rebuild the project for serveral times, it still exits. I am really confused.
Could you please help give me some clues?

Thx & BR

**Comment by lxbsz** [comment]
@zjs1224522500 

This should due to your kernel version is a little bit low, which doesn't contain the following patch:

https://patchwork.kernel.org/patch/10483079/

You can upgrade you kernel version to >= kernel-3.10.0-927.el7, or some other version of 3.10.0-862.X.Y.el7.x86_64 and I am not sure from which version has it.

But this ERROR just one warning message, without it the tcmu-runner should still work for you and it shouldn't block your basic use normally. It is just fixing some bugs.

Thanks,
BRs

**Comment by mikechristie** [comment]
> But I didn't find the handler directory. I have no idea about how to add user:file to the targetcli.

When you do make install you should see where things are installed to if you did not pass in a path:

make install
...
-- Installing: /usr/lib64/tcmu-runner/handle_xyz.so
..

If you are already did a make install then you see

-- Up-to-date: /usr/lib64/tcmu-runner/handler_xyz.so

So in both cases about the tcmu-runner handler dir is /usr/lib64/tcmu-runner

**Comment by zjs1224522500** [comment]
@lxbsz Thanks for your help! But this ERROR blocked my basic use. If I kept the old version of the kernel, I can't start the tcmu-runner successfully. And I can't use the functions provided by tcmu-runner.
In targetcli, the backstores will be like this (without user:xyz):
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 1]
  | | o- lun1 ........................................................................... [/dev/sdb (278.5GiB) write-thru activated]
  | |   o- alua ................................................................................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................. [Storage Objects: 2]
  | | o- FILE1 .................................................................... [/root/tcmu_file (50.0MiB) write-back activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- FILE2 .................................................................. [/root/tcmu_file_2 (50.0MiB) write-back activated]
  | |   o- alua ................................................................................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]

So I can't use the self-define tcmu_handler.
Must I update the version of Kernel to solve the problem?

Thx & BR

**Comment by lxbsz** [comment]
@zjs1224522500 

To be support the tcmu better, you'd better upgrade the kernel. We are fixing many bugs and adding many new features in later release versions.

Yours is 3.10.0-693.el7.x86_64, this is two low, not sure will it work well. We usually limit to use >= 3.10.0-862.14.4.el7.x86_64 for some reason.

As Mike mentioned, please check your install location:

`# ls  /usr/lib64/tcmu-runner/`

If you are not doing it like:

`# cmake -DSUPPORT_SYSTEMD=ON -DCMAKE_INSTALL_PREFIX=/usr .`

Then please make sure you setup is clean, it should be nothing in:

`# ls /usr/local/lib64/tcmu-runner/`

Thanks.

**Comment by zjs1224522500** [comment]
@lxbsz 
I am really sorry to have a misunderstanding about the tcmu-runner process.
Because it will end if I execute `./tcmu-runner` when the process is already running, so I thought the bash will run in backend automatically. And the function is ok in my old version kernel. And I will try to upgrade our kernel version.
Now all issues have been fixed! Thanks for your help and enthusiasm.
Also thank @mikechristie. Thanks for your great work!

Thx & BR
