### ISSUE TITLE
Add new dependencies in self-define handler.

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/tcmu-runner#576]
Hi guys:
     In my handler-xxx.c, I need to insert and update some data in mysql, so I used header file `mysql.h`. But when I execute `./make_runnerrpms.sh`, some errors happened. 

```
fatal error: mysql.h: No such file or directory
```

     Maybe I need to add dependencies in `CMakeLists.txt`. But I am not good at CMake.
     Could you please give me clues?

Thx & BR

**Comment by lxbsz** [comment]
@zjs1224522500 
You may should use  `#include <mysql/mysql.h>` instead.

Thanks.

**Comment by zjs1224522500** [comment]
@lxbsz Thank you firstly!
    With your introduction, now I can build the project successfully. But when I run tcmu-runner, it looks like calling the `dlopen()` method failed. The error msg in log is like following:
```
2019-07-22 11:14:09.353 23753 [ERROR] open_handlers:159: Could not open handler at /usr/lib64/tcmu-runner/handler_mysql.so: /usr/lib64/tcmu-runner/handler_mysql.so: undefined symbol: mysql_query
```
     I am not sure if I need to import the library in other ways except `include<mysql/msyql.h>`.

Thanks.
Best Regards.

**Comment by lxbsz** [comment]
Could you check : 
`# ldd handler_XXX.so`

And for your handler you man need to do something like what the glfs handler to do for dependency of  gfapi.

Thanks.

**Comment by zjs1224522500** [comment]
@lxbsz Thanks a lot！
After adding the library in `CMakeLists.txt` like the glfs handler, the tcmu-runner can run successfully!
Thanks for your help~ Have a nice day!

Thx & BR
