### ISSUE TITLE
How to parse the iovec array to char array or any other formated data structure?

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/tcmu-runner#578]
Hi guys:

-  In my scenario, I want to use Mysql DB as the backend storage for a test. So I need to write the handler by myself and implement the write() and read() method.  And I met a trouble when I tried to convert the data in iovec array to char array in order to write correct SQL to insert the data in DB.

-  I found that there exists a method named `tcmu_memcpy_from_iovec()` in `api.c`. And I also reasearched the the ceph-rbd handler. The rbd.c used the char array bounce_buffer to store the iovec temporarily.

---
```C
static int tcmu_rbd_aio_write(struct tcmu_device *dev, struct rbd_aio_cb *aio_cb,
			      rbd_completion_t completion, struct iovec *iov,
			      size_t iov_cnt, size_t length, off_t offset)
{
	struct tcmu_rbd_state *state = tcmur_dev_get_private(dev);
	int ret;

	aio_cb->bounce_buffer = malloc(length);
	if (!aio_cb->bounce_buffer) {
		tcmu_dev_err(dev, "Failed to allocate bounce buffer.\n");
		return -ENOMEM;;
	}

	tcmu_memcpy_from_iovec(aio_cb->bounce_buffer, length, iov, iov_cnt);

	ret = rbd_aio_write(state->image, offset, length, aio_cb->bounce_buffer,
			    completion);
	if (ret < 0)
		free(aio_cb->bounce_buffer);
	return ret;
}
```

- So I guess if I can use the char array to store the data in iovec and concat string with SQL clause in order to insert the data to the DB. However I found I failed, the char array is empty when I use `%s` to format the data and `strlen` also returned zero.
- I am confused about how the ceph-rbd convert the block io request to the OSD io request. Especially on how to parse the iovec array. Could anyone give me some clues?

Thanks
Best Regards

**Comment by lxbsz** [comment]
@zjs1224522500 

The IO data to/from the kernel space is formatted and stored in the iovec arrary, but the rbd APIs will use the bounce buffer instead, so there will be the data buffer gathered/scattered before/after that callout. 

After reading done, it will scatter the data in bounce buffer into one or more smaller buffers into iovec arrary.
Before writing started, it will gather all the small buffers into a bounce buffer.

Maybe you can try to debug it by printing each iovec info, something like:

nbd_info("iovec->iov_len[%d] iovec->iov_base[%s]\n", iovec->iov_len, iovec->iov_base);

To see is there any data exist ?

**Comment by zjs1224522500** [comment]
@lxbsz Thank you firstly!
- But as for iovec array, the `%s` seems like not suitable for `void *`. So I have to cast the `void *` to `char *`.
```
/* Structure for scatter/gather I/O. */
struct iovec{
     void *iov_base; /* Pointer to data. */
     size_t iov_len; /* Length of data. */
};
```
-  And I use tcmu_err temporarily to print like following code.
```
void print_iovec(struct iovec *iov, size_t iov_cnt)
{
    int i;
    for (i = 0;; i < iov_cnt; i++)
    {
        tcmu_err("iovec->iov_len[%zu] iovec->iov_base[%s].\n", iov->iov_len, (char *) (iov->iov_base));
        iov++;
    }
}
```
- The partial log result is like following: (All iov_base are empty.)
```
2019-07-29 17:04:06.445 7672 [ERROR] print_iovec:769: iovec->iov_len[4096] iovec->iov_base[].
2019-07-29 17:04:06.445 7672 [ERROR] print_iovec:769: iovec->iov_len[61440] iovec->iov_base[].
```
- Maybe I can't use `char *` to cast the value and `%s` also may changed the data format. So I am confused about that the char array `bounce_buffer` in `rbd.c` may be a bridge just for `memcpy()`.

Thanks 
Best Regards

**Comment by lxbsz** [comment]
@zjs1224522500 
Yeah, the data in the iovec arrary not NIL terminated as the string, so you may cannot just do it like this. And it's possible that all the data are zeroed, such as the WRITESAME SCSI command emulator will do. So it not a good idea to cast it to a string as you were concating the string of the SQL clause.

Thanks.

**Comment by zjs1224522500** [comment]
@lxbsz 
Do you have any good ideas to store the data of iovc array? 
I am trying to  find a encode algorithm to convert the data. I am not sure if this method can make sense, I will have a try.
In another way, I may need to have a research about how Ceph-RBD. convert the block io to OSD io. The key point may be the way to convert the iovec array to object storage request.
Thx & BR
