### ISSUE TITLE
consumer.c

### ISSUE THREAD

**Issue by markh794** [open-iscsi/tcmu-runner#597]
Looking for assistance in initial testing of SSC / SMC mhVTL code to utilise tcmu-runner.
As a starting point I was looking at consumer.c

Any tips on how to see this backing store from either targetcli or manually using /sys/....

All I'm after from existing 'consumer' is to be able to respond to 'inquiry'.

Cheers

**Comment by mikechristie** [comment]
Just to make sure we are on the same page because it gets messy.

consumer.c is an example of a daemon that uses libtcmu to do some basic processing including getting/sending commands to the kernel, reading in devices setup in configfs and if needed handling netlink events.

 tcmu-runner is the name of this project and also a daemon in this project that has handlers to convert SCSI commands to ceph, gluster, optical etc requests. It uses libtcmu for setup too.

If you are using consumer.c I am not sure if targetcli works. You might need to slightly change it so it does not always try to talk to a daemon named tcmu-runner or does not try to do some dbus calls. Normally people doing something like consumer.c have gone their own route and might be doing their own setup tools as well as daemon, so on this GH we do not really know what they do.

At the very least the format/steps you need to use in configfs is:

1. modprobe target_core_user
2. cd /sys/kernel/config/target/core
3. mkdir user_$N

here we must use "user" to tell the kernel we are using the target_core_user module, then $N must be a unique numerical id.

4. cd user_0

5. mkdir $device_name

Here device_name can be any user defined string to identify your device.

6. cd device_name

7. You can then write whatever you want to the control file with the dev_config argument for your daemon to use. The kernel will format that as:

tcm-user/<hba_num>/<device_name>/dev_config

tmcu-user is just a prefix used by the module.
hba_num is the $N in the user string from # 3.
device_name is the name from # 5.
dev_config is the string that comes after the dev_config argument.

For example for tcmu-runner and consumer.c you would do:

echo "dev_config=foo/any_other_variables_you_want_to_pass_the_daemon" > control

consumer's call to tcmulib_initialize will then loop over the devices you have setup in the kernel and setup them up for your daemon.

To setup the target part like iscsi, loop, fc, etc then you should read the targetcli/rtslib/lio docs. That setup is the same for tcmu and other backends like file and iblock.

Note that tcmu-runner the daemon has a sort of funky setup workflow in that targetcli/rtslib talks to configfs, configfs interacts with lio and the target_core_user module then that module does netlink to the daemon.

If you are not going to use targetlci/rtslib then you can have your daemon/tools interact with configfs directly and skip the netlink steps which some people do not like.

**Comment by markh794** [comment]
Thanks for the pointers.
I haven't decided what/how to manage configuration at this stage (as mhVTL already has an existing setup/config process) - Once I have something that compiles and responds to 'TUR' or 'INQUIRY', I think I'll be in a better place to decide what/how to handle device setup between tcmu-runner & mhVTL.
As a starting point, I thought I'd merge some of the op-codes and at least have something to show.

p.s. Is this the best place to ask questions - or is there an email/discussion forum anywhere ?

**Comment by markh794** [comment]
newbe question #2 :
Assume I finally get something to show up under /sys/class/uio/* (I did once but not been able to reproduce at the moment)..
How do I get some sort of initiator to connect to my target ?
Seeing my 'lab' is a laptop with virtual box - I'm assuming it's going to be iSCSI (but I'm not fussed what initiator is)

**Comment by markh794** [comment]
I have to admit I'm struggling to find a way to bind the /loopback to the user:foo /backstores/user:foo
Any pointers would be most welcome. (be it loopback or iSCSI - I'm not that fussy)

**Comment by mikechristie** [comment]
> p.s. Is this the best place to ask questions - or is there an email/discussion forum anywhere ?

For userspace this is the best place.

For kernel, target-devel is the best place.

**Comment by mikechristie** [comment]
> I have to admit I'm struggling to find a way to bind the /loopback to the user:foo /backstores/user:foo
> Any pointers would be most welcome. (be it loopback or iSCSI - I'm not that fussy)

I am not sure what you need. Can you even make a iscsi target and create a LUN using one of the existing normal old backstore like iblock or file? Here is the basics: how to make a target, create a backstore, and map it to a LUN using targetcli:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/storage_administration_guide/index#osm-target-setup

**Comment by markh794** [comment]
Setup: I think I have this right now.. I end up with a class/uio/uio0

modprobe  target_core_user
./consumer


In another ssh:


[root@mhvtltcmu-localdomain markh]# cd /sys/kernel/config/target/core
[root@mhvtltcmu-localdomain core]# mkdir user_0
[root@mhvtltcmu-localdomain core]# cd user_0
[root@mhvtltcmu-localdomain user_0]# mkdir foo
[root@mhvtltcmu-localdomain user_0]# cd foo
[root@mhvtltcmu-localdomain foo]# echo "dev_config=foo/mhvtl-device=10" > control
[root@mhvtltcmu-localdomain foo]# echo -n 1 > enable
[root@mhvtltcmu-localdomain foo]# cd /sys/class/uio/
[root@mhvtltcmu-localdomain uio]# ls -l
total 0
lrwxrwxrwx. 1 root root 0 Oct 25 09:09 uio0 -> ../../devices/tcm_user/uio/uio0
[root@mhvtltcmu-localdomain uio]# cd uio0/
[root@mhvtltcmu-localdomain uio0]# ls -l
total 0
-r--r--r--. 1 root root 4096 Oct 25 09:09 dev
lrwxrwxrwx. 1 root root    0 Oct 25 09:09 device -> ../../../tcm_user
-r--r--r--. 1 root root 4096 Oct 25 09:09 event
drwxr-xr-x. 3 root root    0 Oct 25 09:09 maps
-r--r--r--. 1 root root 4096 Oct 25 09:09 name
drwxr-xr-x. 2 root root    0 Oct 25 09:09 power
lrwxrwxrwx. 1 root root    0 Oct 25 09:09 subsystem -> ../../../../class/uio
-rw-r--r--. 1 root root 4096 Oct 25 09:09 uevent
-r--r--r--. 1 root root 4096 Oct 25 09:09 version


And 'targetcli' reports:


[root@mhvtltcmu-localdomain markh] # targetcli
targetcli shell version 2.1.fb49
Copyright 2011-2013 by Datera, Inc and others.
For help on commands, type 'help'.

/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 0]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  | o- user:fbo ............................................................................................... [Storage Objects: 0]
  | o- user:glfs .............................................................................................. [Storage Objects: 0]
  | o- user:qcow .............................................................................................. [Storage Objects: 0]
  | o- user:rbd ............................................................................................... [Storage Objects: 0]
  | o- user:zbc ............................................................................................... [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 0]
  o- loopback ......................................................................................................... [Targets: 0]
/> 


The piece I'm struggling with is:
How to attach/bind/connect the user:foo object with an iSCSI target

Creating the iSCSI target is OK:

[root@mhvtltcmu-localdomain markh] # targetcli /iscsi/ create "iqn.2019-10.com.foo:target"
Created target iqn.2019-10.com.foo:target.
Created TPG 1.
Global pref auto_add_default_portal=true
Created default portal listening on all IPs (0.0.0.0), port 3260.

I'll check out the above reading material..

**Comment by markh794** [comment]
I'm thinking my answers lay somewhere in the following : 
http://linux-iscsi.org/wiki/ConfigFS
http://linux-iscsi.org/wiki/Target/configFS
If anybody knows off the top of their heads - feel free in jumping in :)

**Comment by mikechristie** [comment]
You just map the backend device you created to a LUN under the target. Check out the redhat.com doc above.

**Comment by markh794** [comment]
hmm... Still missing something here - sorry.

A snapshot of some of the options I've tried.. Some I wasn't expecting to work - but tried it anyway.
The ~/.targetcli/log.txt doesn't help either..

/> /iscsi/iqn.2019-10.com.foo:target/
/iscsi/iqn.20...om.foo:target> ls
o- iqn.2019-10.com.foo:target ............................................................................................ [TPGs: 1]
  o- tpg1 ................................................................................................... [no-gen-acls, no-auth]
    o- acls .............................................................................................................. [ACLs: 1]
    | o- iqn.1994-05.com.redhat:e284d58153b4 ...................................................................... [Mapped LUNs: 0]
    o- luns .............................................................................................................. [LUNs: 0]
    o- portals ........................................................................................................ [Portals: 1]
      o- 0.0.0.0:3260 ......................................................................................................... [OK]
/iscsi/iqn.20...om.foo:target> cd tpg1/
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/user:foo/uio0
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/user:foo/foo
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/uio0
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/uio/uio0
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/uio/uio0/
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create
Missing required parameter storage_object
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/uio
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/uio/uio0
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/user:foo/uio0
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/user:foo/uio
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> luns/ create /backstores/user:foo/foo
storage object or path not valid
/iscsi/iqn.20...o:target/tpg1> pwd
/iscsi/iqn.2019-10.com.foo:target/tpg1
/iscsi/iqn.20...o:target/tpg1> 

$ cat /sys/class/uio/uio0/name
tcm-user/0/foo/foo/mhvtl-device=10

**Comment by markh794** [comment]
not sure if it makes any difference but:

# targetcli --version
/bin/targetcli version 2.1.fb49

**Comment by mikechristie** [comment]
I think maybe you just want to use tcmu-runner and write a backend for that. Just look at file_optical.c. It is going to handle this stuff for you.

Also that targetcli version is really old. Just get the current version of targetcli-fb and rtslib-fb form the GitHub.com/open-iscsi repos.

**Comment by markh794** [comment]
Thanks for the tips..
Looked at installing the -fb but wasn't real sure what to do with the tar.gz (I'm sure I would have figured it out eventually)..
Went down the 'file_optical' route instead.
cp file_optical.c file_mhvtl.c (yeah - will fix later)
Updated CMakeLists.txt
/fbo/mhvtl/g -> file_mhvtl.c
make
make install
(OK, here I cheated and rebooted - I do need to identify the service to restart)

I now have a 'user:mhvtl' backstore :)

[markh@mhvtltcmu-localdomain tcmu-runner]$ sudo targetcli /backstores/ ls
o- backstores ................................................................................................................ [...]
  o- block .................................................................................................... [Storage Objects: 0]
  o- fileio ................................................................................................... [Storage Objects: 0]
  o- pscsi .................................................................................................... [Storage Objects: 0]
  o- ramdisk .................................................................................................. [Storage Objects: 0]
  o- user:fbo ................................................................................................. [Storage Objects: 0]
  o- user:glfs ................................................................................................ [Storage Objects: 0]
  o- user:mhvtl ............................................................................................... [Storage Objects: 0]
  o- user:qcow ................................................................................................ [Storage Objects: 0]
  o- user:rbd ................................................................................................. [Storage Objects: 0]
  o- user:zbc ................................................................................................. [Storage Objects: 0]

closing this - as I'll go down the 'file_optical.c' route instead of consumer.c
