### ISSUE TITLE
'size', 'level', and 'config' must be set when creating a new UserBackedStorageObject

### ISSUE THREAD

**Issue by 676384417** [open-iscsi/tcmu-runner#605]
Help! How to work around this issue...

/backstores/user:zbc> ls
o- user:zbc ................................................................................. [Storage Objects: 0]
/backstores/user:zbc> create name=zbc0 size=20G cfgstring=model-HM/zsize-256/conv-10@/var/local/zbc0.raw
'size', 'level', and 'config' must be set when creating a new UserBackedStorageObject
/backstores/user:zbc>

**Comment by lxbsz** [comment]
This works in Fedora with fresh installed. You are using Ubuntu release, for me I didn't test this in Ubuntu env, so please try this installing them from source.

```
/> cd backstores/user:zbc 
/backstores/user:zbc> create name=zbc0 size=20G cfgstring=model-HM/zsize-256/conv-10@/var/local/zbc0.raw
Created user-backed storage object zbc0 size 21474836480.
/backstores/user:zbc> exit
Global pref auto_save_on_exit=true
Last 10 configs saved in /etc/target/backup/.
Configuration saved to /etc/target/saveconfig.json


targetcli-2.1.fb49-2.fc30.noarch
python3-rtslib-2.1.fb69-3.fc30.noarch
tcmu-runner-1.4.1-1.fc30.x86_64

```
