### ISSUE TITLE
Can't recovery tpg from disable to enable.

### ISSUE THREAD

**Issue by AresChen1** [open-iscsi/tcmu-runner#607]
OS: Centos 7.6.1810
Version: ceph-13.2.5 + tcmu-runner-1.4.1
When ceph pool is fault, it will return timeout to tcmu-runner, and create a recovery thread and disable the tpg. The device can only be added into tpg->devs one time in tcmu_add_dev_to_recovery_list called by tcmu_notify_conn_lost. But from the logs, the device maybe added into tpg->devs more than one times:

> 2019-12-30 17:54:47.797 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.799 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.808 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.810 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.828 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.830 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.869 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.871 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.876 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.878 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.878 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.880 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
> 2019-12-30 17:54:47.888 12783 [ERROR] tcmu_rbd_handle_timedout_cmd:996 rbd/mixpool.vlmix: Timing out cmd.
> 2019-12-30 17:54:47.890 12783 [ERROR] tcmu_notify_conn_lost:209 rbd/mixpool.vlmix: Handler connection lost (lock state 1)
Maybe cause:
     The `ret` in `tcmu_add_dev_to_recovery_list` not inited, if it finds the tpg on `tpg_recovery_list`, it will goto the `add_to_list` and will return the `ret` that is not inited. And it will not set the flags with `TCMUR_DEV_FLAG_IN_RECOVERY`.  When come timeout again, it maybe add the same device into the `tpg->devs` twice times. When the recovery thread `tgt_port_grp_recovery_thread_fn` process the `tpg->devs` with `list_for_each_safe`,  it always get the same node that added twice times.

**Comment by mikechristie** [comment]
> > The `ret` in `tcmu_add_dev_to_recovery_list` not inited, if it finds the tpg on `tpg_recovery_list`, it will goto the `add_to_list` and will return the `ret`

ret is not initialized at the top of the function. It will be zero if we get to:

```
        /*
         * This assumes a tcmu_dev is only exported though one local
         * enabled tpg. The kernel members file only returns
         * the one and runner is not passed info about which
         * tpg/port IO was received on.
         */
        list_for_each(&alua_list, group, entry) {
```

because a couple lines above that we do:

```
        list_head_init(&alua_list);
        ret = tcmu_get_alua_grps(dev, &alua_list);
        if (ret) {
                /* User is deleting device so fast fail */
                tcmu_dev_warn(dev, "Could not find any tpgs.\n");
                goto done;
        }
```

so if tcmu_get_alua_grps returns failure, ret will non-zero and we will hit the "goto done". If that function returns success, ret will be zero, and then we will continue to run the function and do the loop above. If the loop detects the port is on the recovery list already then we will return 0. tcmu_notify_conn_lost should then set the TCMUR_DEV_FLAG_IN_RECOVERY bit.

**Comment by mikechristie** [comment]
Are you hitting one of the errors paths in tcmu_add_dev_to_recovery_list where ret != 0?  If you did, we would normally see another error message, but there are those 2 cases where we log a warning only:

```
                /* User is deleting device so fast fail */
                tcmu_dev_warn(dev, "Could not find any tpgs.\n");
```

or do not log anything:

```
        tpg = setup_tgt_port_grp(enabled_port);
        if (!tpg) {
                ret = -ENOMEM;
                goto done;
        }
```

**Comment by AresChen1** [comment]
We use tcmu-runner that version is 1.4.1, But we patch the code `https://github.com/open-iscsi/tcmu-runner/pull/596`, so it does not have the list code in `tcmu_add_dev_to_recovery_list`:
`list_head_init(&alua_list);
        ret = tcmu_get_alua_grps(dev, &alua_list);
        if (ret) {
                /* User is deleting device so fast fail */
                tcmu_dev_warn(dev, "Could not find any tpgs.\n");
                goto done;
        }
`

**Comment by AresChen1** [comment]
We use tcmu-runner that version is 1.4.1, But we patch the code #https://github.com/open-iscsi/tcmu-runner/pull/596, so it does not have the list code in `tcmu_add_dev_to_recovery_list`:
```
list_head_init(&alua_list);
	ret = tcmu_get_alua_grps(dev, &alua_list);
	if (ret) {
		/* User is deleting device so fast fail */
		tcmu_dev_warn(dev, "Could not find any tpgs.\n");
		goto done;
	}
````

**Comment by mikechristie** [comment]
Ah ok, I am working on a different patch for 596 which will fix the other bug you reported where we can still deadlock during deletion. I am on vacation until Jan 6th. When I am back next week I will post a new PR with a fix for all the issues.

I uploaded a updated version of the 596 patch in that PR patch with the "ret = 0" issue change, if you need a quick temp fix.

Going to close this since it's not related to the upstream code or a release and is a bug with a specific PR that is still open.
