### ISSUE TITLE
systemctl start tcmu-runner error, how to find error info?

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/tcmu-runner#620]
I use `systemctl start tcmu-runner` to run tcmu-runner, and it failed. So I try to use systemctl status tcmu-runner to view details. But I have no clues about why this error happen.
```
tcmu-runner.service - LIO Userspace-passthrough daemon
   Loaded: loaded (/usr/lib/systemd/system/tcmu-runner.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-04-10 10:17:43 CST; 11s ago
     Docs: man:tcmu-runner(8)
  Process: 9805 ExecStart=/usr/bin/tcmu-runner (code=exited, status=203/EXEC)
 Main PID: 9805 (code=exited, status=203/EXEC)

Apr 10 10:17:43 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: Starting LIO Userspace-passthrough daemon...
Apr 10 10:17:43 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: tcmu-runner.service: main process exited, code=exited, status=203/EXEC
Apr 10 10:17:43 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: Failed to start LIO Userspace-passthrough daemon.
Apr 10 10:17:43 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: Unit tcmu-runner.service entered failed state.
Apr 10 10:17:43 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: tcmu-runner.service failed.
```

I also checkd the log file in `/var/log/tcmu-runner.log`. There is no any valid info. 
So could you give me some clues about how to find the error occured?

BTW, I wrote a tcmu handler by myself. It may be the major reason. But I don't know how to fix this because of lack of some error info.

**Comment by lxbsz** [comment]
Could you see any errors in the `journalctl`  log ?

**Comment by zjs1224522500** [comment]
- Yeah, I see the errors in `journalctl` log. And I try to fix it with the error msg.
```
Apr 10 10:49:22 ecs-sn3-medium-2-linux-20200222090658 systemd-logind[545]: New session 5 of user root.
-- Subject: A new session 5 has been created for user root
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 5 has been created for the user root.
-- 
-- The leading process of the session is 10031.
Apr 10 10:49:22 ecs-sn3-medium-2-linux-20200222090658 sshd[10031]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 10 10:49:27 ecs-sn3-medium-2-linux-20200222090658 dbus[546]: [system] Activating via systemd: service name='org.kernel.TCMUService1' unit='tcmu-runner.service'
Apr 10 10:49:52 ecs-sn3-medium-2-linux-20200222090658 dbus[546]: [system] Failed to activate service 'org.kernel.TCMUService1': timed out
Apr 10 10:50:05 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: tcmu-runner.service start operation timed out. Terminating.
Apr 10 10:50:05 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: Failed to start LIO Userspace-passthrough daemon.
-- Subject: Unit tcmu-runner.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit tcmu-runner.service has failed.
-- 
-- The result is failed.
Apr 10 10:50:05 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: Unit tcmu-runner.service entered failed state.
Apr 10 10:50:05 ecs-sn3-medium-2-linux-20200222090658 systemd[1]: tcmu-runner.service failed.
Apr 10 10:50:05 ecs-sn3-medium-2-linux-20200222090658 polkitd[544]: Unregistered Authentication Agent for unix-process:10001:302134 (system bus name :1.18, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, local
lines 1424-1477/1477 (END)
```

**Comment by zjs1224522500** [comment]
@lxbsz After I tried to re-build and install for several times, now it can run normally. 
But I have a question about how to find the library used by my own handler `handler_xyz.so`.
I change the CMakeLists.txt as : (And I confirmed that the libraries are in the given paths.)
```
list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/s3-c/test/lib")
list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/install/usr/local/lib64")
list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/s3util/lib")

find_library(AWSCORE aws-cpp-sdk-core)
find_library(AWSS3 aws-cpp-sdk-s3)
find_library(S3Shared s3shared)
find_library(S3SharedC s3sharedC)

add_library(handler_xyz
  SHARED
  handler_hikvision_file.c
  )
set_target_properties(handler_xyz
  PROPERTIES
  PREFIX ""
  )
target_include_directories(handler_xyz
  PUBLIC ${PROJECT_SOURCE_DIR}/ccan
  /c++/C-Example/linux/install/usr/local/include
  /c++/C-Example/linux/s3util/include
  /c++/C-Example/linux/s3-c/test/include
  )
target_link_libraries(handler_xyz ${AWSCORE} ${AWSS3} ${S3Shared} ${S3SharedC})
install(TARGETS handler_xyz DESTINATION ${CMAKE_INSTALL_LIBDIR}/tcmu-runner)
```
 - And build successfully, but when I run tcmu-runner, the log in `/var/log/tcmu-runner.log` shows:
```
open_handlers:160: Could not open handler at /usr/lib64/tcmu-runner/handler_xyz_file.so: libaws-cpp-sdk-core.so: cannot open shared object file: No such file or directory
```

- Is there some extra configuration need to be set?

**Comment by lxbsz** [comment]
> @lxbsz After I tried to re-build and install for several times, now it can run normally.
> But I have a question about how to find the library used by my own handler `handler_xyz.so`.
> I change the CMakeLists.txt as : (And I confirmed that the libraries are in the given paths.)
> 
> ```
> list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/s3-c/test/lib")
> list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/install/usr/local/lib64")
> list(APPEND CMAKE_LIBRARY_PATH "/c++/C-Example/linux/s3util/lib")
> 
> find_library(AWSCORE aws-cpp-sdk-core)
> find_library(AWSS3 aws-cpp-sdk-s3)
> find_library(S3Shared s3shared)
> find_library(S3SharedC s3sharedC)
> 
> add_library(handler_xyz
>   SHARED
>   handler_hikvision_file.c
>   )
> set_target_properties(handler_xyz
>   PROPERTIES
>   PREFIX ""
>   )
> target_include_directories(handler_xyz
>   PUBLIC ${PROJECT_SOURCE_DIR}/ccan
>   /c++/C-Example/linux/install/usr/local/include
>   /c++/C-Example/linux/s3util/include
>   /c++/C-Example/linux/s3-c/test/include
>   )
> target_link_libraries(handler_xyz ${AWSCORE} ${AWSS3} ${S3Shared} ${S3SharedC})
> install(TARGETS handler_xyz DESTINATION ${CMAKE_INSTALL_LIBDIR}/tcmu-runner)
> ```
> 
> * And build successfully, but when I run tcmu-runner, the log in `/var/log/tcmu-runner.log` shows:
> 
> ```
> open_handlers:160: Could not open handler at /usr/lib64/tcmu-runner/handler_xyz_file.so: libaws-cpp-sdk-core.so: cannot open shared object file: No such file or directory
> ```
> 
> * Is there some extra configuration need to be set?

No other need to be set, it seems that the  libaws-cpp-sdk-core.so is not correctly added to the lib path.

**Comment by zjs1224522500** [comment]
@lxbsz So could you have some clues for how to add the library xxx.so to the lib path?
I tried to write a simple C test code. It also return same error message as tcmu-runner.
```
#include <stdio.h>
#include <dlfcn.h>

int main() {
    char* path = "/usr/lib64/tcmu-runner/handler_hikvision_file.so";
    void *handle = dlopen(path, RTLD_NOW|RTLD_LOCAL);
	if (!handle) {
	    printf("Could not open handler at %s: %s\n", path, dlerror());
	} else {
        printf("Success");
    }
    free(path);
    return 0;
}
```

**Comment by lxbsz** [comment]
@zjs1224522500 Sorry, I may missed you last comment, did you resolve it ?

**Comment by zjs1224522500** [comment]
> @zjs1224522500 Sorry, I may missed you last comment, did you resolve it ?

Yeah, I resolved it by copying the library to directoy /usr/lib64.

**Comment by lxbsz** [comment]
> > @zjs1224522500 Sorry, I may missed you last comment, did you resolve it ?
> 
> Yeah, I resolved it by copying the library to directoy /usr/lib64.

Okay.
