### ISSUE TITLE
does rbd.user allow user change wwn's attrib ?

### ISSUE THREAD

**Issue by zhujing3** [open-iscsi/tcmu-runner#624]
with backstores/block mode, i can change it 

so i try to do this on user:rbd, any tips ? thx a lot

cd /sys/kernel/config/target/core/user_0/rbd.v-aabbccdd/wwn
[root@node01 wwn]# 
[root@node01 wwn]# 
[root@node01 wwn]# echo "TEST" > vendor_id
-bash: echo: write error: Invalid argument
[root@node01 wwn]# echo "TEST" > product_id
-bash: echo: write error: Invalid argument
[root@node01 wwn]# echo "TEST" > vpd_unit_serial
-bash: echo: write error: Invalid argument

**Comment by mikechristie** [comment]
When you do the echo, what is the error message in the kernel? Check out /var/log/messges or journalctl.

You are probably trying to change the value after the device is mapped which is not allowed.

If you are using tcmu-runner and targetcli then you can change these values in the /etc/target/savedconfig.json file. If you are using tcmu-runner with ceph-iscsi there is no setting to change it.
