### ISSUE TITLE
[ERROR] tcmu_cfgfs_set_str:294: Kernel does not support configfs file

### ISSUE THREAD

**Issue by NUABO** [open-iscsi/tcmu-runner#625]
hi，
I am using centos7.5 , kernel version is 3.10.0-862.el7.x86_64, tcmu version is 1.5.2, when starting tcmu-runner, the following error appears

>[root@controller ceph_iscsi]# cat  /var/log/tcmu-runner.log
2020-05-08 11:38:35.395 36489:tcmu-runner [CRIT] main:1269: Starting...
2020-05-08 11:38:35.402 36489:tcmu-runner [INFO] load_our_module:548: Inserted module 'target_core_user'
**2020-05-08 11:38:35.402 36489:tcmu-runner [ERROR] tcmu_cfgfs_set_str:294: Kernel does not support configfs file /sys/module/target_core_user/parameters/block_netlink.**

Will this error affect use ？

**Comment by mikechristie** [comment]
As long as you are not manually starting/stopping tcmu-runner manually you will be ok under normal conditions. You should start/stop the ceph-iscsi services rbd-target-api/gw first and they will make sure IO is stopped/flushed safely.

The kernel in Centos 7.7/7.8 has the needed changes that support block/unblock_netlink so you can stop tcmu-runner manually while IO is running.
