### ISSUE TITLE
How to config optimal_io_size of block device created by tcmu-runner?

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/tcmu-runner#635]
- I found that the block device created by using tcmu-runner is strange. 
- In following output
  - `/dev/sdb` is a physical disk with `I/O size (minimum/optimal): 512 bytes / 512 bytes`
  - `/dev/sdd` is iscsi disk created by using tcmu-runner with `I/O size (minimum/optimal): 512 bytes / 65536 bytes`
```
Disk /dev/sdb: 1199.0 GB, 1198999470080 bytes, 2341795840 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sdd: 1073 MB, 1073741824 bytes, 2097152 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 65536 bytes
```
- You can find `optimal_io_size` is different in disks. In fact, I don't know much about the `I/O size (minimum/optimal)`. 
- I have some questions.
  - How do these two params work in actual I/O behaviors?
  - Can we config the specific value for these two params in tcmu-runner?

**Comment by lxbsz** [comment]
The 512 Bytes is from the value of the `hw_block_size`, which as default in LIO will be 512 Bytes, and you can also configure it when you are creating the device. This is the minimum size of the disk controller will read/write each time, and it will also affect the pysical DMA behaviour in pysical iscsi devices.  If you are doing the IOs, you'd better align your data buffer to `hw_block_size` at least to improve the perf.

The `optimal_io_size` will be the optimal data size recommand to be for each IO, in LIO code it set to 128 sectors as default, that is 128 * 512 Bytes. In ceph-iscsi it will be set to 1024 sectors. This will depend on the disk controller's DMA or something else for the pysical iscsi device. For the tcmu-runner it will depends on the backends ceph/gluster,etc and also the network packages limit. Just to follow this it will improve your IO perf mostly.

**Comment by zjs1224522500** [comment]
- Thanks for your reply firstly~
- As for `hw_block_size`, I can config in `targetcli` by using the parameter when creating the block device. For `optimal_io_size`, as we implement self-define tcmu-handler (so it is different from internal backend), is there any way to config the `optimal_io_size` for tcmu-handler implemented by ourselves?

**Comment by lxbsz** [comment]
> * Thanks for your reply firstly~
> * As for `hw_block_size`, I can config in `targetcli` by using the parameter when creating the block device. For `optimal_io_size`, as we implement self-define tcmu-handler (so it is different from internal backend), is there any way to config the `optimal_io_size` for tcmu-handler implemented by ourselves?

For `optimal_io_size`, you should config `hw_max_sectors` when creating the device.

**Comment by zjs1224522500** [comment]
> > * Thanks for your reply firstly~
> > * As for `hw_block_size`, I can config in `targetcli` by using the parameter when creating the block device. For `optimal_io_size`, as we implement self-define tcmu-handler (so it is different from internal backend), is there any way to config the `optimal_io_size` for tcmu-handler implemented by ourselves?
> 
> For `optimal_io_size`, you should config `hw_max_sectors` when creating the device.

Thanks a lot!

**Comment by zjs1224522500** [comment]
> The 512 Bytes is from the value of the `hw_block_size`, which as default in LIO will be 512 Bytes, and you can also configure it when you are creating the device. This is the minimum size of the disk controller will read/write each time, and it will also affect the pysical DMA behaviour in pysical iscsi devices. If you are doing the IOs, you'd better align your data buffer to `hw_block_size` at least to improve the perf.
> 
> The `optimal_io_size` will be the optimal data size recommand to be for each IO, in LIO code it set to 128 sectors as default, that is 128 * 512 Bytes. In ceph-iscsi it will be set to 1024 sectors. This will depend on the disk controller's DMA or something else for the pysical iscsi device. For the tcmu-runner it will depends on the backends ceph/gluster,etc and also the network packages limit. Just to follow this it will improve your IO perf mostly.

- I have yet another question. 
- For `optimal_io_size`, it is the optimal data size recommend to be for each IO. And I evaluated some applications (eg.`leveldb` and `dd`) on the block device created by tcmu-runner handler, and I log the I/O size in read/write method provided by tcmu-handler. In the evaluation result, 64KB is the most common IO size as we use default `hw_max_sectors=128sectors`, and there also are different-size IOs.
- How does the `optimal_io_size` take effect in actual IO behaviors? In my perspective, applications may read the param `optimal_io_size` of the block device and decide the specific IO size. Or OS used the `optimal_io_size` to batch IO?
- Thanks for your reply in advance!

**Comment by lxbsz** [comment]
> > The 512 Bytes is from the value of the `hw_block_size`, which as default in LIO will be 512 Bytes, and you can also configure it when you are creating the device. This is the minimum size of the disk controller will read/write each time, and it will also affect the pysical DMA behaviour in pysical iscsi devices. If you are doing the IOs, you'd better align your data buffer to `hw_block_size` at least to improve the perf.
> > The `optimal_io_size` will be the optimal data size recommand to be for each IO, in LIO code it set to 128 sectors as default, that is 128 * 512 Bytes. In ceph-iscsi it will be set to 1024 sectors. This will depend on the disk controller's DMA or something else for the pysical iscsi device. For the tcmu-runner it will depends on the backends ceph/gluster,etc and also the network packages limit. Just to follow this it will improve your IO perf mostly.
> 
> * I have yet another question.
> * For `optimal_io_size`, it is the optimal data size recommend to be for each IO. And I evaluated some applications (eg.`leveldb` and `dd`) on the block device created by tcmu-runner handler, and I log the I/O size in read/write method provided by tcmu-handler. In the evaluation result, 64KB is the most common IO size as we use default `hw_max_sectors=128sectors`, and there also are different-size IOs.

Why it set to be 128 sectors in LIO code, should be considering the network package MTU up limit, which should be 64K. Larger than 128 should make no sense.

> * How does the `optimal_io_size` take effect in actual IO behaviors? In my perspective, applications may read the param `optimal_io_size` of the block device and decide the specific IO size. Or OS used the `optimal_io_size` to batch IO?

Have you tried to set a smaller value and see what will happen for the IO size ?

> * Thanks for your reply in advance!

**Comment by zjs1224522500** [comment]
@lxbsz I tried to config `hw_max_sectors` to 64 sectors (32KB) and retest the applications.  In the evaluation result, 32KB is the most common IO size.

**Comment by lxbsz** [comment]
> @lxbsz I tried to config `hw_max_sectors` to 64 sectors (32KB) and retest the applications. In the evaluation result, 32KB is the most common IO size.

Yeah, this is expected. 64K is the upper limit for MTU, so the max IO size should be min(MTU, optimal_io_size).

**Comment by zjs1224522500** [comment]
> > @lxbsz I tried to config `hw_max_sectors` to 64 sectors (32KB) and retest the applications. In the evaluation result, 32KB is the most common IO size.
> 
> Yeah, this is expected. 64K is the upper limit for MTU, so the max IO size should be min(MTU, optimal_io_size).

So the `min(MTU, optimal_io_size)` is executed by OS or applications?

**Comment by lxbsz** [comment]
> > > @lxbsz I tried to config `hw_max_sectors` to 64 sectors (32KB) and retest the applications. In the evaluation result, 32KB is the most common IO size.
> > 
> > 
> > Yeah, this is expected. 64K is the upper limit for MTU, so the max IO size should be min(MTU, optimal_io_size).
> 
> So the `min(MTU, optimal_io_size)` is executed by OS or applications?

IMO, it should be in iscsi layer in kernel space, but not very sure, you can have a check.

**Comment by zjs1224522500** [comment]
@lxbsz I tried to set `hw_max_sectors` to 256 sectors (128KB) and retest the applications. In the evaluation result, 128KB is the most common IO size.
So the io size may not be decided by `min(MTU, optimal_io_size)`. And I have checked the kernel code and didn't find the `min(MTU, optimal_io_size)`.

**Comment by lxbsz** [comment]
> @lxbsz I tried to set `hw_max_sectors` to 256 sectors (128KB) and retest the applications. In the evaluation result, 128KB is the most common IO size.
> So the io size may not be decided by `min(MTU, optimal_io_size)`. And I have checked the kernel code and didn't find the `min(MTU, optimal_io_size)`.

The above is expected, and the  `hw_max_sectors` will always equal to  `optimal_io_size` for tcmu-runner.
