### ISSUE TITLE
What does nr_threads in tcmur_handler mean?

### ISSUE THREAD

**Issue by YouDieInADream** [open-iscsi/tcmu-runner#637]
I am confused about the `nr_threads` in tcmur_handler. Can I use this parameter to decide how many threads can be used for cmd handle?

**Comment by lxbsz** [comment]
> Thanks for your reply! @lxbsz
> If I implement my handler **without** aio methods, this parameter `nr_threads` can help me enable aio framework. Is it right?

That's right.

> If I implement my handler **with** aio methods, how does the parameter `nr_threads` take effect?
If you have implement the aio methods in your handler, you could just set `nr_threads` to 0 to use the aio methods in your own handler. If you still need it, you could just set it to a number than 1. But be careful if you want to set it to a number larger than 1.

**Comment by YouDieInADream** [comment]
I am sorry to disturb you again~ 
I have one more question about `nr_threads`.

In my implementation, for every request, it will execute one I/O operation on my storage system (such as a simple file, object store or other storage systems).
If I set the `nr_threads` greater than 0 (eg.16) and implement my handler without aio methods, it means that there may be 16 threads running in parallel to handle requests. 
**Do I need to guarantee the accuracy of concurrent access to the storage system by myself?** 

Thanks @lxbsz

**Comment by lxbsz** [comment]
> **Do I need to guarantee the accuracy of concurrent access to the storage system by myself?**
> 

Yeah, you need.

**Comment by lxbsz** [comment]
Closing this issue, if needed please reopen it.
