### ISSUE TITLE
rbd: compare-and-write non-atomic for stripe-units less than block size

### ISSUE THREAD

**Issue by ddiss** [open-iscsi/tcmu-runner#641]
LIO permits single block compare-and-write SCSI requests. These requests must be handled atomically such that the write portion is applied in its entirety (if compare succeeds) or not at all.
For RBD images with a stripe unit less than the SCSI block size, a compare-and-write request will cross RADOS object boundaries for the RBD image, thus losing atomicity.

I'm not aware of librbd logic that checks for this condition, but I haven't checked closely. Without such a check, I think the best option would be to check the stripe unit during LUN configuration and fail if it's less than the block size.

cc @dillaman

**Comment by dillaman** [comment]
How do you set the physical block size larger than the stripe unit?

**Comment by ddiss** [comment]
target_core_user / tcmu-runner uses a `hw_block_size=512` default. RBD images can use a stripe unit of e.g. 256 bytes. A compare-and-write request with such a setup spans two RADOS objects.

**Comment by dillaman** [comment]
Fair enough -- we should validate stripe unit in librbd to ensure people aren't attempting to use crazy invalid values -- but this seems like it's a librbd issue not a tcmu-runner.

**Comment by dillaman** [comment]
Tracking here: https://tracker.ceph.com/issues/47828

**Comment by ddiss** [comment]
Thanks. FWIW a 4K SCSI block size would still cause breakage if the minimum were set to 512, so I think detecting this in tcmu-runner (during LUN configuration) would still make sense.

libiscsi's `CompareAndWrite.Miscompare` unit test offers a reproducer for this issue.

**Comment by dillaman** [comment]
Do you really see this in the wild or is this more hypothetical?  librbd should already restrict compare-and-write to single object extents so if it doesn't, I'll need to investigate.

**Comment by ddiss** [comment]
> Do you really see this in the wild or is this more hypothetical?

For tcmu-runner/librbd it's only hypothetical. I reproduced it with kRBD while adapting @mikechristie 's target_core_rbd compare-and-write patches to support fancy-striping.

> librbd should already restrict compare-and-write to single object extents so if it doesn't, I'll need to investigate.

Ah okay. In that case feel free to close it here if that's the case (sorry for the noise).

**Comment by dillaman** [comment]
> Ah okay. Feel free to close this ticket if that's the case (sorry for the noise).

No worries, I think it's definitely valid to restrict the stripe-unit to a sane value. For librbd, it should fail here [1]

[1] https://github.com/ceph/ceph/blob/master/src/librbd/io/ImageRequest.cc#L811
