### ISSUE TITLE
precompiled rpms

### ISSUE THREAD

**Issue by mathrock74** [open-iscsi/tcmu-runner#653]
Please supply precompiled rpms for latest version on https://shaman.ceph.com/

thank you

**Comment by lxbsz** [comment]
Done. Thanks.

**Comment by mathrock74** [comment]
Thank you very much, but could you also provide rpms for EL7?

**Comment by lxbsz** [comment]
> Thank you very much, but could you also provide rpms for EL7?

Sorry, that build won't work for the el7.

**Comment by mathrock74** [comment]
> > Thank you very much, but could you also provide rpms for EL7?
> 
> Sorry, that build won't work for the el7.

does that mean that tcmu-runner can't be used on RHEL/CentOS 7 anymore?

**Comment by lxbsz** [comment]
No, I didn't see any limiation that it won't work on el7, for now you need to build the el7 packages by yourself.
