### ISSUE TITLE
A possible deadlock issue

### ISSUE THREAD

**Issue by ryancaicse** [open-iscsi/tcmu-runner#681]
It seems that lock `rdev->caw_lock` is not released before Line 1736. Should it be a bug?
https://github.com/open-iscsi/tcmu-runner/blob/b4d1656ecc5500b85416e1014669669434ddb291/tcmur_cmd_handler.c#L1731-L1736

**Comment by lxbsz** [comment]
No, please check the `handle_caw_read_cbk/handle_caw_write_cbk`, the lock will be released there later for aio.

**Comment by ryancaicse** [comment]
@lxbsz Thank you for your reply!
