### ISSUE TITLE
question:  can tcmu-runner be configured to work with ceph running on a different vm?

### ISSUE THREAD

**Issue by lknite** [open-iscsi/tcmu-runner#700]
I've deployed ceph via rook (kubernetes), but exposing iSCSI seems to require kernel interaction so I'm trying to setup tcmu-runner on the host system and having that interact with ceph.  I think this should easily be doable if tcmu-runner can be configured with a remote ceph cluster.

tcmu-runner probably assumes by default it's on a ceph node, to make this work I could probably setup some port forwarding if I knew what to forward, however it would be more clean and convenient to provide connection details to access the ceph cluster ... in my case this "remote ceph cluster" configuration would actually being pointing to ceph running in kubernetes on the local node so it should be fast enough.

Alternatively, if someone else has iSCSI working with a rook-based ceph installation working in some other way let me know and I can use that method instead.

**Comment by lxbsz** [comment]
Certainly it could. The tcmu-runner will be just a client of the rbd.

**Comment by lknite** [comment]
Great, could you point me in the right direction on how one might configure it to do that?  So far I've only seen the documentation on the github main page.

**Comment by lxbsz** [comment]
You can refer to the ceph iscsi docs: https://docs.ceph.com/en/quincy/rbd/iscsi-overview/

**Comment by lknite** [comment]
I had already read that documentation before posting the question and was looking for some additional assistance.  Just hearing it was possible and being redirected to the docs completely killed all motivation to incorporate this project so... closing ticket as no longer investigating this.
